### ISSUE TITLE
Download url returned from "update" endpoint contains undefined version. 

### ISSUE THREAD

**Issue by jayalfredprufrock** [ArekSredzki/electron-release-server#1]
I know this is a new project so not sure if you're ready for bug reports, but I figured I'd share my experience with you just in case.

Here is the url I'm using: 
http://xxx.xxx.xxx.xxx:5014/update/osx_x64/0.0.2

And here is what is returned:
{"url":"http://xxx.xxx.xxx.xxx:5014/download/version/0.0.3/undefined?filetype=zip","name":"0.0.3","notes":"## 0.0.3\nBlah","pub_date":"2016-03-03T22:33:56.224Z"}

I struggled a bit finding the right way to create the update url as well. The docs make it look like the url parameters can be specified in a couple of different ways and I tried just about every combination of urls, query string variables, and platform names until I finally found the one above that worked. Perhaps that's by design, but if so the docs could make it a little more clear :) 

Anyways, super glad somebody put something like this together, I was just about to build something like this myself when I discovered this project. Great job!

**Comment by ArekSredzki** [comment]
@jayalfredprufrock Thank you so much for your input!

I'm actually just about to start integrating this into my project, so I'm sure it's not quite stable yet.
If you would like to help contribute, it would be very much appreciated!

I'll try to look into this issue asap, and keep the issues coming!

**Comment by ArekSredzki** [comment]
@jayalfredprufrock Please let me know if you run into any further issues!
