### ISSUE TITLE
using nonstandard ports

### ISSUE THREAD

**Issue by mikey0000** [ArekSredzki/electron-release-server#101]
So we've been trying to use this on a non-standard port and the returned download url does not have the port in it.

**Comment by ArekSredzki** [comment]
Hi @mikey0000 
The generated download url uses the `appUrl` variable that's configured in `./config/local.js` Ensure that you add the port there :)

**Comment by ArekSredzki** [comment]
Pull requests are welcome if you think that this could be clarified somewhere.

**Comment by mikey0000** [comment]
Great will see if theres somewhere nice to add it to. Thanks for the clarification as well.
