### ISSUE TITLE
Always returning 500 "Version not found"

### ISSUE THREAD

**Issue by Dave93** [ArekSredzki/electron-release-server#103]
Hi.
I'm trying open such url: /update/windows_64/0.0.0/RELEASES and always get error "Version not found", therefore electron auto updater throws errors.
Could you help me to solve this issue?

**Comment by ArekSredzki** [comment]
Version 0.0.0 must be a valid version for this to work. However, you shouldn't have a version of that name, so you should be using something like 0.0.1

**Comment by Dave93** [comment]
Thanks a lot for quick answer.
I tried to use another version http://c2n.me/3FftkX7 http://c2n.me/3FftrZ5.

**Comment by ArekSredzki** [comment]
What assets do you have for 0.0.1?
Also, what about if you try `/update/win64/0.0.1/stable/RELEASES`
