### ISSUE TITLE
Software License

### ISSUE THREAD

**Issue by nbering** [ArekSredzki/electron-release-server#11]
I stumbled across this from the electron docs, so I would have assumed this was under an open source license. Checking quickly brought me to the conclusion that this is completely unlicensed, and as such defaults to copyright law which reserves all right to retain ownership and prevent use or modification of the code.

Is there any plan to release this under an open source license? Or at least provide some clarification on whether we have permission to use this project, if you aren't going to put one of the generic licenses on it?

**Comment by ArekSredzki** [comment]
@nbering great catch, and that was an honest mistake. I'll push out a new license in an hour.

**Comment by ArekSredzki** [comment]
@nbering Resolved by 90404da18c92484b2cec6822d0d096c5e27683c9
