### ISSUE TITLE
Local cache of versions?

### ISSUE THREAD

**Issue by gilvandev** [ArekSredzki/electron-release-server#112]
After installing the server on my local machine, I managed to launch 2 versions: 5.0.1 and 5.0.2. But I don't know for what reason, by launching the version 5.0.3 and try to access the URL of update, the server returns a 500 error saying that version does not exist.

Removed all other versions and still get the error. Did deploy again in another folder and still insists on it. Cleaned browsers cache, I used Google Chrome, Mozilla, and Opera. Even after the deploy (believe) it was still possible to access the old versions (5.0.1 and 5.0.2). What the hell is that? Would be some temporary folder that wasn't clean?

Even in my application electron, when you try to check for updates, the application also receives an error 500 (in case the application is at version 5.0.3)

**Comment by ArekSredzki** [comment]
What versions are available on the server and do they have assets for your platform?

**Comment by gilvandev** [comment]
Available: 5.0.1, 5.0.2 and 5.0.3. and all have assets (nupkg) but only the most recent (5.0.3) have an a exe asset.

**Comment by ArekSredzki** [comment]
Does it work if they all have exe assets?

**Comment by gilvandev** [comment]
No. Error 500. I try delete all versions and clean the phyton database. Equals
