### ISSUE TITLE
Version list is not populating.

### ISSUE THREAD

**Issue by l2thet** [ArekSredzki/electron-release-server#123]
I can add new versions and they're created in the DB but they won't display under version management. I don't get any errors in the console and no errors in 'npm start' console that I am running. When I attempt to add the same version number twice I get an error that the version already exists, so it's definitely saving and being cross checked, it just won't display. Please let me know what other details to provide.

**Comment by LeAcid** [comment]
I am also getting this same error

**Comment by quarthex** [comment]
May relate to issue #96

**Comment by l2thet** [comment]
I'm not sure it's related as I'm not running nginx, this is just a straight out of the box. I did some tinkering with the code base yesterday night and the only way I could get it to work was to insert an ajax call to populate DataService in version-table-controller.js. Once that was there I could upload assets and such, so I don't think this is a firewall issue either. :(

**Comment by quarthex** [comment]
I get the issue with Squid. It works with direct access, for me.

**Comment by SJ-AW** [comment]
My version are created in the database but they won't display under version management. I don't use nginx and  I dont get any errors. Popup "version created successfully" appears but  "new version available" doesn't appear... Did I miss something in my database configuration or in my local.js file?
Sorry for my english

**Comment by MarshallOfSound** [comment]
Same issue, logs appear to indicate it's a websocket issue.  @quarthex did you get anywhere with this issue?

**Comment by SJ-AW** [comment]
No sorry

**Comment by MarshallOfSound** [comment]
@SJ-AW Don't suppose you were using Amazon's load balancing as well? 😆 Think I'm onto something here

**Comment by SJ-AW** [comment]
No I used electron-release-server locally for test but I failed. I suppose I miss something. So now I use electron-builder with GitHub.

**Comment by MarshallOfSound** [comment]
Well for anyone who comes across this setting this up in AWS, don't forget that ELB doesn't support WebSockets without extreme magic 👍

**Comment by g-borgulya** [comment]
Had the same problem using nginx. Setting the right headers for the proxy in nginx solved the problem:

```
	location / {
		proxy_pass_header Server;
		proxy_set_header Host $host;
		proxy_redirect off;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection 'upgrade';
		proxy_set_header X-Real_IP $remote_addr;
		proxy_set_header X_Scheme $scheme;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_cache_bypass $http_upgrade;
		proxy_pass http://electron-release-server;
	}
```

I'm not sure which setting from these does the trick, I found the solution with trial and error.
