### ISSUE TITLE
Feature: Let users select executable architecture

### ISSUE THREAD

**Issue by ArekSredzki** [ArekSredzki/electron-release-server#13]
We can reliably automatically detect the system platform from the browser user-agent.
However, this cannot be said for their system architecture, which is either 64 or 32 bit.

For Windows and Linux users, they should be presented to choose from the available architectures.

**Comment by shoaibmerchant** [comment]
We can try using https://github.com/faisalman/ua-parser-js it is quite popular, if it can provide a valid answer for architecture we can proceed with it else fallback to user selection.

**Comment by ArekSredzki** [comment]
This functionality was added three months ago, that's why the issue was closed.
