### ISSUE TITLE
Alpha channel can get the stable channel .nupkg file

### ISSUE THREAD

**Issue by weihong1028** [ArekSredzki/electron-release-server#131]
When the latest version is stable, I can get the stable channel .nupkg file with a alpha channel request.
![wechatimg140](https://cloud.githubusercontent.com/assets/7336582/25984001/a17b67a0-371a-11e7-986d-d52bd9eb0da3.jpeg)

**Comment by ArekSredzki** [comment]
I believe that what you're getting at is desired behaviour. The alpha channel will expose all updates that are _at least as reliable as_ the alpha channel. That includes alpha beta and stable (perhaps others that I've forgotten). If the issue is something else, please reopen this ticket 🙂

**Comment by weihong1028** [comment]
OK，Thanks!
