### ISSUE TITLE
Grunt Error at starting server

### ISSUE THREAD

**Issue by himanshu21092** [ArekSredzki/electron-release-server#135]
Hi

I am trying to start server for the first time and I am getting the following error.

> error: ** Grunt :: An error occurred. **
> error:
> ------------------------------------------------------------------------
> Aborted due to warnings.
> Running "wiredep:task" (wiredep) task
> Warning: Task "sass:dev" not found.
> ------------------------------------------------------------------------
> 
> error: Looks like a Grunt error occurred--
> error: Please fix it, then **restart Sails** to continue running tasks (e.g. watching for ch
> anges in assets)
> error: Or if you're stuck, check out the troubleshooting tips below.

Please help

**Comment by Alanzote** [comment]
You can try (in linux):
`npm install --global yo bower grunt-cli 
bower install --allow-root`
It worked for me.

**Comment by Liiion911** [comment]
> You can try (in linux):
> `npm install --global yo bower grunt-cli`
> `bower install --allow-root`
> It worked for me.


error: ** Grunt :: An error occurred. **
error:
------------------------------------------------------------------------
>> Error: File to import not found or unreadable: ../bower_components/bootstrap-sass-official/assets/stylesheets/_bootstrap.scss.
>>         on line 4 of assets/styles/importer.scss
>> >> @import '../bower_components/bootstrap-sass-official/assets/stylesheets/_boo
>>    ^
Warning:

Aborted due to warnings.
Running "sass:dev" (sass) task

**Comment by ArekSredzki** [comment]
@Liiion911 Is this an issue you're still having?

**Comment by jdforsythe** [comment]
I'm having this issue with the Docker container. Fresh clone, run:

```sh
docker-compose up -d
docker logs -f electron-release-server_web_1
```

```txt
wait.sh: waiting 15 seconds for db:5432
wait.sh: db:5432 is available after 0 seconds

> electron-release-server@1.5.2 start /usr/src/electron-release-server
> node app.js

info: 
info:                .-..-.
info: 
info:    Sails              <|    .-..-.
info:    v0.12.14            |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in `/usr/src/electron-release-server`
info: To see your app, visit http://localhost
info: To shut down Sails, press <CTRL> + C at any time.

debug: -------------------------------------------------------

debug: :: Fri Nov 08 2019 16:36:16 GMT+0000 (Coordinated Universal Time)
debug: Environment : development
debug: Port        : 80
debug: -------------------------------------------------------
error: ** Grunt :: An error occurred. **
error: 
------------------------------------------------------------------------
Aborted due to warnings.
Running "wiredep:task" (wiredep) task
Warning: Cannot find module 'mout/lang' 
------------------------------------------------------------------------

error: Looks like a Grunt error occurred--
error: Please fix it, then **restart Sails** to continue running tasks (e.g. watching for changes in assets)
error: Or if you're stuck, check out the troubleshooting tips below.

error: Troubleshooting tips:
error: 
error:  *-> Are "grunt" and related grunt task modules installed locally?  Run `npm install` if you're not sure.
error: 
error:  *-> You might have a malformed LESS, SASS, CoffeeScript file, etc.
error: 
error:  *-> Or maybe you don't have permissions to access the `.tmp` directory?
error:      e.g., `/usr/src/electron-release-server/.tmp` ?
error: 
error:      If you think this might be the case, try running:

error:      sudo chown -R YOUR_COMPUTER_USER_NAME /usr/src/electron-release-server/.tmp
```
