### ISSUE TITLE
How to setup auto-updater on windows

### ISSUE THREAD

**Issue by dengyaolong** [ArekSredzki/electron-release-server#137]
> to the Squirrel.Windows documentation on how to setup your application.

Now I use electorn-builder generate exe and nupkg, then upload to release-server.

I set auto-updater
```
const { autoUpdater } = electron
autoUpdater.feedbackurl = `${myReleaseServerHost}/update/${os_platform}_${os_arch}/version`
autoUpdater.checkForUpdates()
```
But It doesn't requeset my release server, and throw error"can't not find sequrriel" ? And I just want to know how to set up autoUpdater use release-server and electron-builder?

**Comment by ArekSredzki** [comment]
You should use `autoUpdater.setFeedURL(url[, requestHeaders])` rather than setting the variable directly.
See [this page](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md) for more information.
