### ISSUE TITLE
SSL Disable

### ISSUE THREAD

**Issue by saigopi** [ArekSredzki/electron-release-server#139]
Hi, I am testing this for our uat env. 

I don't want to use ssl. how can I turn off ssl.

**Comment by ArekSredzki** [comment]
I should warn that certain (all?) platforms require the use of SSL for security reasons. It's very easy to obtain an SSL cert these days, I'd recommend doing so. That said, I'm not sure that there's anything in the release server forcing you to do so. Where are you running into problems?

**Comment by saigopi** [comment]
Thank you Arek.
