### ISSUE TITLE
Getting exceptions

### ISSUE THREAD

**Issue by manpreetrsystems** [ArekSredzki/electron-release-server#140]
Hi,

I am getting a exception as
 "**[warn] Error: Command failed: 4294967295 System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
 at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) "**

What could be the possible reason and solution.
![untitled](https://user-images.githubusercontent.com/30076452/28575590-00281bd4-716f-11e7-82b8-4909e6d5c42a.png)

**Comment by ArekSredzki** [comment]
What happens when you navigate to that URL in your browser?

**Comment by manpreetrsystems** [comment]
@ArekSredzki :The exe gets downloaded upon hitting the url on the browser.

**Comment by ArekSredzki** [comment]
@manpreetrsystems squirrel sends some headers along with the request. try using a tool like Postman to intercept the request and see what's going on. That or look at the log from the server itself :) This might be happening because an asset file was deleted for a specific os/arch.

**Comment by manpreetrsystems** [comment]
@ArekSredzki :ok: How can I get logs from electron release server??

**Comment by ArekSredzki** [comment]
This depends how you’re running it. They are output to stdout so are in your shell window if run directly. If you are using docker or pm2 then those tools have ways for accessing the program output.

**Comment by ArekSredzki** [comment]
Can this be closed?

**Comment by manpreetrsystems** [comment]
@ArekSredzki - Actuuly I used Postman to get the reponse from the server but upon hitting the url , Postman is getting hanged and I am not able to get the required information and I am still getting 404 as earlier. So while using electron auto updater I have commented out the update download method and wrote my own method which will download and save the exe on local disk . So , this is the only solution that I got.
Yes, You can close the ticket .
