### ISSUE TITLE
Setting setFeedURL (Electron autoUpdater) correctly

### ISSUE THREAD

**Issue by Alanzote** [ArekSredzki/electron-release-server#143]
I've noticed that setFeedURL to http://download.mysite.com/updates/win32/RELEASES actually adds query parameters to it. Anyone knows how to force autoUpdater not to add query parameters?

**Comment by manpreetrsystems** [comment]
I got the same issue regarding the feedURL, but instead of setting URL as "http://download.mysite.com/updates/win32/RELEASES" , I gave the URL as "http://localhost/download/1.0.1/windows_32/app.exe", but now I am getting a 404 error from the server.

**Comment by maxiiss** [comment]
Hello,
I have quite the same difficulty. I assume my electron release server is deployed correctly ( I can get the RELEASE file), but I have errors with the AutoUpdate process concerning the URL.
Did you solve your problem ? Could anyone help me ?

**Comment by tymmesyde** [comment]
The correct working path is https://yoursite.com/update/win64/1.0.1/stable

**Comment by gliss** [comment]
To anyone that may still be stuck when setting the update URL **don't** include **RELEASES** as the autoupdater function appends it to the url. 

Example my app was sending a get request to 
`/update/win64/4.0.0/RELEASES/RELEASES?id=my-app&localVersion=1.0.0&arch=amd64`

and I had set my URL to
```
const updateServer = 'https://download.example.com';
let arch = process.arch === 'x64' ? 'win64' : 'win32';
const feed = `${updateServer}/update/${arch}/${app.getVersion()}/RELEASES`;
```
Removing RELEASES from the const feed fix my problem
