### ISSUE TITLE
API to create new version/upload files

### ISSUE THREAD

**Issue by hammy2899** [ArekSredzki/electron-release-server#145]
I am currently creating a CI process to build and deploy my app and I am wondering if there is a feature in the API to create a new version and upload files to the release server if not could you add this in the future?

This would be really helpful to automatically deploy apps using CI.

**Comment by shearer12345** [comment]
I'd be interested in this also :)

**Comment by shearer12345** [comment]
should've looked through the issue - this feature already exists - thanks @ArekSredzki for building this tool - I really like it.

@hammy2899 - using the API is described in #36 and #79
