### ISSUE TITLE
/home respnose with http status code 404 , but still have corrent html content body

### ISSUE THREAD

**Issue by happymachine** [ArekSredzki/electron-release-server#147]
hello there, 

If I request to   example.com/home  , I will got a https status code 404 : 

![1 1](https://user-images.githubusercontent.com/30713917/30055260-784eee0e-9261-11e7-800c-d31784c6bdfa.jpg)

However, in this request,  the content body is correct : 

![2](https://user-images.githubusercontent.com/30713917/30055281-89196e6c-9261-11e7-9cbb-cedae8de9574.jpg)

is there anyone can help ?   it suppose to response with http status code 200.

**Comment by miguelangelvlc94** [comment]
Any updates @happymachine ? I have the same problem.

**Comment by DustinBrett** [comment]
I have a PR in to solve this. https://github.com/ArekSredzki/electron-release-server/pull/206
