### ISSUE TITLE
Override uploaded file name?

### ISSUE THREAD

**Issue by achingbrain** [ArekSredzki/electron-release-server#149]
Unless I'm missing something I can't upload files with the same name as different versions and/or to different channels.

If this is unsupported, would it be possible to specify a `fileName` argument when uploading an asset that would override the actual name of the uploaded file?

**Comment by DustinBrett** [comment]
I have a PR in currently to achieve this and several other changes to assets.

https://github.com/ArekSredzki/electron-release-server/pull/204
