### ISSUE TITLE
[FR] Track download statistics

### ISSUE THREAD

**Issue by Ilshidur** [ArekSredzki/electron-release-server#159]
I was wondering how to save the downloads count on a time series database, like [InfluxDB](https://github.com/influxdata/influxdb). One use case would be to monitor downloads count over time, for example.

I think one good solution is [StatsD](https://www.npmjs.com/package/statsd). It would be awesome to have monitoring solutions for this awesome project !

Maybe there are simpler solutions (that I couldn't figure out), but I'm curious about how to achieve this :-)

**Comment by beliaev-maksim** [comment]
@ArekSredzki, @Ilshidur , @DustinBrett 

I think we are already tracking downloads in Assets, don't we ?
![image](https://user-images.githubusercontent.com/51964909/84832674-02317000-b02e-11ea-9a24-ff9efa4fd649.png)

so is the question to postprocess data from Database or also add another table into DB "time vs download vs version vs asset" ?
or is the idea to add completely new implementation maybe with Graphite + StatsD?
