### ISSUE TITLE
Should return 204 instead of 500 when no update is available

### ISSUE THREAD

**Issue by linjackson78** [ArekSredzki/electron-release-server#167]
I created a version named '0.1.0' on server, it is expected to return 204 when I `GET /update/win32/0.1.0/releases`, but it returns 500 with message 'Version not found'.

Looks like a response of 500 would make Squirrel unhappy and throw out exception, this looks like a bug of electron-release-server.

Is there going to be a fix?

**Comment by abdurrahmanekr** [comment]
I have that same problem.

**Comment by ArekSredzki** [comment]
Is this still an issue? Otherwise, this should be closed soon.

**Comment by abdurrahmanekr** [comment]
I don't know if a code has been written for the solution. However, to resolve this issue, I return the latest version of windows if the user requested an update for windows.

**Comment by ArekSredzki** [comment]
@DustinBrett does your recent PR relate to this?

**Comment by DustinBrett** [comment]
> @DustinBrett does your recent PR relate to this?

I don't believe so. Not intentionally at least.
