### ISSUE TITLE
update url with localhost

### ISSUE THREAD

**Issue by ChristianLimes** [ArekSredzki/electron-release-server#171]
I run release-server in docker an configure it for localhost usage. Everything works fine but when I call http://127.0.0.1:5000/update/darwin_x64/0.1.0, I get this back.

`{
  "url": "localhost:/download/0.2.0/osx_64?filetype=zip",
  "name": "0.2.0",
  "notes": "",
  "pub_date": "2017-11-30T15:13:00.000Z"
}`

I'm running on port 5000 did I forget to change something in the config file? I set the appUrl to `appUrl: 'http://localhost:5000',` in config/local.js

**Comment by nellyLidanYang** [comment]
Could you post how did you solve this?
