### ISSUE TITLE
One release server, multiple apps 

### ISSUE THREAD

**Issue by itsmebhavin** [ArekSredzki/electron-release-server#176]
I have a case where we have one release server setup on production server which is serving one app updates as of now.  We are making another app for the same client and so i would like to know how can i use same release server which serve two or more apps thru interface. 

Thanks,

**Comment by DustinBrett** [comment]
While this may not be exactly what you are looking for I have created a PR with the idea of "flavors" of an app. Our use case is different clients using nearly the same app but with slight changes for white labeling purposes. Maybe you can repurpose the code or use it as is to achieve your desired result.

https://github.com/ArekSredzki/electron-release-server/pull/202

**Comment by ArekSredzki** [comment]
This should be available in v1.5.0
Please open a new ticket if the implemented solution doesn't meet your needs
