### ISSUE TITLE
prerelease version update detect question

### ISSUE THREAD

**Issue by weihong1028** [ArekSredzki/electron-release-server#180]
When I create a new prerelease version, It says may additionally be followed by a whole number.

<img width="568" alt="2018-01-24 12 53 30" src="https://user-images.githubusercontent.com/7336582/35289004-27ccf3aa-00a1-11e8-8d5b-5a4de7fd8e1c.png">

But I ran into some trouble, I have three version 2.2.8-rc7 / 2.2.8-rc10 / 2.2.8-rc11, when I try to detect the new version from 2.2.8-rc7, It just can not find the 2.2.8-rc11, see the screenshot.

<img width="713" alt="2018-01-24 12 59 34" src="https://user-images.githubusercontent.com/7336582/35289301-e5f631c0-00a1-11e8-8791-67fff6ac1dba.png">
<img width="949" alt="2018-01-24 1 00 53" src="https://user-images.githubusercontent.com/7336582/35289366-192974bc-00a2-11e8-94a3-008e62ddda4c.png">

And I try to detect the new version from 2.2.8-rc10, It can find the 2.2.8-rc11.

<img width="939" alt="2018-01-24 1 01 09" src="https://user-images.githubusercontent.com/7336582/35289420-4782f810-00a2-11e8-9302-14642ff58a6f.png">

Can you help me?

**Comment by ArekSredzki** [comment]
Hi, Thanks for your bug report!
It would appear that there is a period required between the prerelease type & prerelease number

I've verified this with the command line version of the `semver` npm package (which is used by the release server).

```
~ semver -i prerelease 2.2.8-rc7 
2.2.8-rc7.0
~ semver -i prerelease 2.2.8-rc.7
2.2.8-rc.8
~ semver -i prerelease 2.2.8-rc10
2.2.8-rc10.0
~ semver -i prerelease 2.2.8-rc.10
2.2.8-rc.11
```

As such, please change your release versions to have a period. A merge request adding a period to the GUI text would be much appreciated if you have a spare moment!

**Comment by weihong1028** [comment]
Thanks a lot, and I will try to add a merge request.

**Comment by weihong1028** [comment]
#181

**Comment by weihong1028** [comment]
reference #181
