### ISSUE TITLE
docker-compose up -d fails in local : No such file or directory

### ISSUE THREAD

**Issue by weeger** [ArekSredzki/electron-release-server#183]
Hi,

Just cloned the repo on a Windows machine running Docker Toolbox.

`docker-compose up -d` => the web container stops
`docker logs xxx_web` => `: No such file or directory`

I have created the local.js file but nothing changes.

Thanks,

**Comment by weeger** [comment]
Seems we have a problem with `wait.sh` : the server start when I remove the entrypoint of the docker-compose.yml file

**Comment by weeger** [comment]
Found : CRFL / LF issue... ;)

**Comment by yx208** [comment]
> Seems we have a problem with `wait.sh` : the server start when I remove the entrypoint of the docker-compose.yml file

You're right!
