### ISSUE TITLE
Error On Login

### ISSUE THREAD

**Issue by LYC-kosic** [ArekSredzki/electron-release-server#188]
I need to create a local Electron Release Server for development.
But after finish to configure the authentication settings (include static, LDAP), I fail on login.
I have tried the static and LDAP login but all fail.
When I check on the console log, it displays the 500 internal server error.
And the command line has shown the "TypeError: Cannot read property 'token_secret' of undefined".
But I do not have the enough knowledge with sails to solve the issue.
Am I still miss some configure to build it?

Here is my auth of local.js:

```
auth: {
       static: {
          username: 'user',
          password: '1234'
        },
        ldap: {
          usernameField: 'uid',
          server: {
            url: 'ldap://localhost:10389',
            bindDn: 'uid=jdoe,ou=User,ou=ActiveMQ,ou=system',
            bindCredentials: '1234',
            searchBase: 'ou=user,ou=ActiveMQ,ou=system',
            searchFilter: '(uid={{username}})'
          }
}

```

**Comment by LYC-kosic** [comment]
Sorry, I have found out the problem....

**Comment by Malnasser** [comment]
what's the problem?
