### ISSUE TITLE
error: error: password authentication failed for user "electron_release_server_user"

### ISSUE THREAD

**Issue by tylerl0706** [ArekSredzki/electron-release-server#19]
I was trying to throw the release server up on an Azure Ubuntu 14.04 VM.

I followed all of the steps that I followed in order to get this working on OS X locally but I'm running in to this issue:

`error: error: password authentication failed for user "electron_release_server_user"`

I know for a fact that my credentials are correct because

`psql -U electron_release_server_user -h localhost electron_release_server` 

seems to work fine when it prompts me to put the password in.

My local.js includes:

```
connections: {
    postgresql: {
      adapter: 'sails-postgresql',
      host: 'localhost',
      user: 'electron_release_server_user',
      password: '',
      database: 'electron_release_server'
    }
  },

  session: {
    secret: '1939DFCED4B55FB4179081E8EBBC22134CCC5E08D3A5CC3A549783BF9DB1D2A2',
    database: 'electron_release_server_sessions',
    host: 'localhost',
    user: 'electron_release_server_user',
    password: '',
    port: 5432
  },
```

Please help as soon as you can. I'm in a bit of a rush to get this out the door.

**Comment by ArekSredzki** [comment]
Hi @tylerl0706

Thank you for reaching out, unfortunately I'm not sure why you are experiencing this issue.
Your postgres server is running on the default port, correct?

**Comment by tylerl0706** [comment]
Hey man! I confirmed that the port is running on the default port.

What I find strange is that this exact config.js works on my local machine
(OS X).

Could this be an Ubuntu thing? Maybe I forgot to install some dependency?
I've opened up a SO issue here:

http://stackoverflow.com/questions/37035592/error-error-password-authentication-failed-for-user-electron-release-server-u/37046835#37046835

I'm on Node 6.0 I believe. Maybe I should use stable instead. I'm also on
Postgres 9.4.

**Comment by ArekSredzki** [comment]
Use node 5

Arek Sredzki
University of British Columbia
BSc 2017 || Computer Science
C: ‭(360) 790 - 3654‬ (Jan - April 2016)
C: (604) 763 - 2217 (May 2016+)
LinkedIn  ||  www.arek.io

**Comment by tylerl0706** [comment]
Yep... That was it lol... This doesn't work with Node 6.0. But I switched
to LTS and it works!

**Comment by tylerl0706** [comment]
While I have you, navigate to: 

`http://40.79.77.106/`

and then navigate to:

`http://download.getboltly.com/`

any reason why the content doesn't load on the second link?

**Comment by tylerl0706** [comment]
If was because cloudflare was minifying the javascript.

**Comment by ArekSredzki** [comment]
Glad to hear, yay!

**Comment by mydansun** [comment]
I have the same problem, and Node.js 5.x works!

**Comment by bapatel1** [comment]
I was having same issue and 5.11.1 fixed it. I would still like to see progress for node v6

**Comment by ShahNewazKhan** [comment]
I ran into the same issue and was able to resolve it as per [http://stackoverflow.com/a/36959873/2990066]
