### ISSUE TITLE
upload file error

### ISSUE THREAD

**Issue by BigSteel** [ArekSredzki/electron-release-server#191]
![wechatimg9](https://user-images.githubusercontent.com/5989219/47848579-c1112b80-de09-11e8-87cb-d83eefbd5d83.png)
![wechatimg10](https://user-images.githubusercontent.com/5989219/47848580-c1112b80-de09-11e8-906b-62b657c05dfb.png)

**Comment by BigSteel** [comment]
myservice is runing on osx.

**Comment by mvkanha** [comment]
I am getting same error @BigSteel  how can i resolve ?

**Comment by BigSteel** [comment]
> I am getting same error @BigSteel how can i resolve ?

1 . check config/local.js ，Make sure the folder exists and has write permissions
![Uploading image.png…]()

**Comment by mvkanha** [comment]
Thanks @BigSteel for solved
