### ISSUE TITLE
docker.js sets session.token_secret instead of session.secret

### ISSUE THREAD

**Issue by regner** [ArekSredzki/electron-release-server#193]
Based on local.template the config should be:

```js
    secret: process.env['TOKEN_SECRET'],
```

However the docker.js file has the following:

```js
    token_secret: process.env['TOKEN_SECRET'],
```

Not actually sure if the jwt.token_secret should be the same as session.secret or not...

**Comment by regner** [comment]
It also looks like the docker.js config is missing `adapter: 'sails-pg-session'`

**Comment by ArekSredzki** [comment]
@DustinBrett Would you be able to look at this?

**Comment by DustinBrett** [comment]
Sure I can look into this.
