### ISSUE TITLE
Error thrown when uploading assets

### ISSUE THREAD

**Issue by oozliuoo** [ArekSredzki/electron-release-server#195]
Hi,

I have successfully deployed the app to my server, and many thanks to the great work from you. However, after the upload process completed, server will throw error as followed and failed to save/serve the uploaded file:

```
Sending 500 ("Server Error") response:
 Error: ENOENT: no such file or directory, open '7b956cf1-9406-4530-92c4-e46e241becfb.zip'
```

I have tried updated the `dirname` in `local.js` and ensured that directory has correct permission for user (in fact, I even tried 0777), but still no luck on this.

It seems the file is not getting stored anywhere, could you please help with this issue and provide more information about the assets storage progress?

Many thanks to you!

**Comment by oozliuoo** [comment]
Since nobody is leaving suggestions, heres what I have done as a temp solution in case anyone ran into the same situation:

1. Update `dirname` in `local.js` with `./`, as shown below:

```javascript


  files: {
    // Folder must exist and user running the server must have adequate perms
    dirname: './',
    // Maximum allowed file size in bytes
    // Defaults to 500MB
    maxBytes: 524288000
  },
```

2. in `AssetController.js`, update the parameter passed into `AssetService.getHash`, as shown below:

```javascript
        if (fileExt === '.nupkg') {
          // Calculate the hash of the file, as it is necessary for windows
          // files
          hashPromise = AssetService.getHash(`.tmp/uploads/${uploadedFile.fd}`);
        } else if (fileExt === '.exe' || fileExt === '.zip') {
          hashPromise = AssetService.getHash(`.tmp/uploads/${uploadedFile.fd}`, 'sha256');
        } else {
          hashPromise = Promise.resolve('');
        }
```

The problem here is that the `dirname` is actually relative to the `.tmp` folder under the project directory, instead of relative to the project root directory. The other way around to make it work could be using `../` in `dirname`.

I'm not sure if this is what is expected, but since I cannot find anything helpful via the doc, this could be a temp solution, and if anything is not necessary, please help adding the correct solution here.

Thanks.

**Comment by nellyLidanYang** [comment]
try modify "dirname" to __dirname. I fixed mine with that

**Comment by TTATPuOT** [comment]
After year issue is actual.
Tick with __dirname works fine, thx @nellyLidanYang 
Solution by @oozliuoo not works, because server not allow to download files, only upload.

But, maybe, @ArekSredzki will fix it?

**Comment by DustinBrett** [comment]
I'm hoping to get to some of these issues in the new year. Had a busy last few months. I will reopen and assign this to myself. If @ArekSredzki has a chance to look at it 1st then great but otherwise it's on my radar.

**Comment by ArekSredzki** [comment]
Thanks @DustinBrett I don’t really have the time to look into these issues these days, it’d be great if you could!

**Comment by phoenix2692** [comment]
Files are getting uploaded but are not reflected in response or in the version management - asset list.
I'm getting similar error response: "Error: ENOENT: no such file or directory, open 'PATH FOR ASSETS/{uuid}.exe'" when tried to upload asset. But on checking, file exists in ".tmp/uploads/PATH FOR ASSETS/" dir.
>Solved
Initially during setup, I had not configured dirname in local.js and had default value "PATH FOR ASSETS". But after setting dirname to "/var/electron/uploads" I was able to get **success response** and was getting listed in management.

For Info :
Process I followed for setting up in my new instance:
[Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-1052-aws x86_64), psql (PostgreSQL) 10.12 (Ubuntu 10.12-2.pgdg16.04+1) (with PostgreSQL 12, getting "orm" error)]
1. Extracted the zip in /home/ubuntu/electron folder.
2. Changed to root user (sudo bash)
3. Copied /home/ubuntu/electron to /var/ directory.
4. npm start -> Server is starting in development env

However, I had followed the same process (an year ago) for another Ubuntu 16 [Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-1077-aws x86_64), psql (PostgreSQL) 11.3 (Ubuntu 11.3-1.pgdg16.04+1)] instance where I've not set the dirname variable and is still working fine.

**Comment by sergio-caro** [comment]
I have to say that neither @oozliuoo solution nor @nellyLidanYang solution worked for me, but a combination of both methods.

Just in case someone is in the same situation as me, this is what I did:

1. Changes made to `config/local.js`:
   - I made a combination of both solutions: Renaming the key `dirname` to `__dirname` and setting the location of the dir to be `./`.
```javascript
  files: {
    // Folder must exist and user running the server must have adequate perms
    __dirname: './',
    // Maximum allowed file size in bytes
    // Defaults to 500MB
    // maxBytes: 524288000
  }
```
2. Changes made to `api/controllers/AssetController.js`:
  - The solution provided by @oozliuoo works, but just only for uploading files to the server. Manually downloading files, with this config/mods, will not work (I did not try apps' updates though, so I don't know if it works). Modification of `.getHash()` calls to add the temp folder.

```javascript
if (fileExt === '.nupkg') {
    // Calculate the hash of the file, as it is necessary for windows
    // files
    hashPromise = AssetService.getHash(`.tmp/uploads/${uploadedFile.fd}`);
} else if (fileExt === '.exe' || fileExt === '.zip') {
    hashPromise = AssetService.getHash(`.tmp/uploads/${uploadedFile.fd}`, 'sha256');
} else {
    hashPromise = Promise.resolve('');
}
```

   - Second, to allow users to manually download files, I made a small modification bellow that previous code. Changes to `fd` attr to be similar to the previous change.

```javascript
hashPromise
    .then(function(fileHash) {
        // Create new instance of model using data from params
        Asset
           .create(_.merge({
              name: uploadedFile.filename,
              hash: fileHash,
              filetype: fileExt,
              fd: `.tmp/uploads/${uploadedFile.fd}`,
              size: uploadedFile.size
   }, data))
```

**Comment by prv123** [comment]
@sergio-caro Thanks, It worked For me...

**Comment by AFatMan** [comment]
@sergio-caro Thanks, It worked For me,
And i change my `nginx.conf` `client_max_body_size 100m`
