### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by ArekSredzki** [ArekSredzki/electron-release-server#2]
The api offered should be extensively unit tested.

Unfortunately I don't have time to dedicate to such a task right now, volunteers are much appreciated!

**Comment by Matrix76** [comment]
-

**Comment by ArekSredzki** [comment]
@DustinBrett Any thoughts on how we could add CI?

**Comment by DustinBrett** [comment]
> @DustinBrett Any thoughts on how we could add CI?

I have a few ideas, I will bookmark this issue for further research.
