### ISSUE TITLE
http://xxx.xxx.xxx/update/win64/1.0.3/stable/RELEASE return value error

### ISSUE THREAD

**Issue by gggin** [ArekSredzki/electron-release-server#21]
http://xxx.xxx.xxx/update/win64/1.0.3/stable/RELEASE

first is md5 or sha1 
second is url to download
but second is http://download/xxxx.nutpackage (there is no HOST!)

**Comment by ArekSredzki** [comment]
@gggin Could you please include the output `http://xxx.xxx.xxx/update/win64/1.0.3/stable/RELEASE`?

I'm not sure what a `nutpackage`, but that's not one of the supported file types, and `http://download/xxxx.nutpackage` should not be the download url.

**Comment by gggin** [comment]
first thank you for answer!
![image](https://cloud.githubusercontent.com/assets/3293064/15210518/72568746-1869-11e6-8f4f-5472b194db66.png)

**Comment by ArekSredzki** [comment]
Have you set your site url in `config/local.js`?

**Comment by gggin** [comment]
sure, just an ip address

**Comment by gggin** [comment]
Thank you! I did not add within http://

**Comment by ArekSredzki** [comment]
Glad to hear 👍
