### ISSUE TITLE
Resolve code quality issues detected by LGTM

### ISSUE THREAD

**Issue by ArekSredzki** [ArekSredzki/electron-release-server#212]
It would be good to resolve the issues detected by LGTM. 
The list can be seen here: https://lgtm.com/projects/g/ArekSredzki/electron-release-server/alerts/

**Comment by DustinBrett** [comment]
Sorry but I accidentally pushed fixes for LGTM into master. I have changed my git client to not allow this kind of push in the future. We can undo it and go the normal PR route which is what I actually wanted to do, but I don't want to mess with master anymore than I already have so I am posting here to notify of the change and to get a chance for you to review this commit. If we can force GitHub to only allow me to make changes to master via a PR, that would be fine with me also.

https://github.com/ArekSredzki/electron-release-server/commit/db10a19ce2c6e24e0f66d82250b35994e12c9128

**Comment by DustinBrett** [comment]
Ideally I'd still rather this go through PR so that LGTM can scan it. I just didn't want to change things further as I didn't realize that the branch I had made was linked/referencing master.

**Comment by ArekSredzki** [comment]
Thanks so much for the fixes. No worries about the accidental push. I think we should just let it be this time. It’s more problematic to revert than I think it’s worth. The changes look good :)

**Comment by ArekSredzki** [comment]
Hrm, it looks like LGTM doesn’t update its analysis of master without a PR. If you want you could push a revert commit to master and then open. PR for your changes. It’s up to you :)

**Comment by DustinBrett** [comment]
> Hrm, it looks like LGTM doesn’t update its analysis of master without a PR. If you want you could push a revert commit to master and then open. PR for your changes. It’s up to you :)

Ah darn, of all the PR's to accidentally push to master, haha. Well I see mention [here](https://lgtm.com/help/lgtm/analysis-faqs#how-often-does-lgtm-check-for-new-commits) of daily scans, so I will wait a day and if it doesn't update I will do the revert PR as you suggest.

**Comment by ArekSredzki** [comment]
I was able to use their API to run an analysis ahead of them scanning for changes in master. Looks like you got all of the issues they detected :) 
https://lgtm.com/projects/g/ArekSredzki/electron-release-server/analysis/57fbe071dd87d7c24be84bbfb2a5ff711dfea1a9/files?sort=alerts&dir=DESC&mode=heatmap&showExcluded=true

The badge in the readme now reads 0 issues 🥇
