### ISSUE TITLE
is PostgreSQL mandatory?

### ISSUE THREAD

**Issue by brendtumi** [ArekSredzki/electron-release-server#22]
i see mongodb option in config/connections.js, but i am not sure is acceptable because no referral on docs. 
Can we use mongodb or maybe just disk db?

**Comment by ArekSredzki** [comment]
@brendtumi You should be able to use any sails adapter. The easiest way of changing the selected adapter is to leave the name the same of the connection as `postgresql` but modifying it's contents.

For example I often use the following in `config/local.js` for development:

```js
  connections: {
    postgresql: {
      adapter: 'sails-disk'
    }
  },
```

**Comment by ArekSredzki** [comment]
Just ensure that you install the appropriate adapter module using npm

**Comment by ArekSredzki** [comment]
If you want to improve the documentation in regards to this, it would be much appreciated :)

Submit a PR and I'll gladly merge it in!
