### ISSUE TITLE
DEV-162 breaks in Microsoft Edge/IE

### ISSUE THREAD

**Issue by andypaxo** [ArekSredzki/electron-release-server#226]
No page renders correctly in the current release when using the most recent version of Edge or Internet Explorer. All pages display only the header and footer.

This seems to be because of a JavaScript error caused by the change to `makeAvailable` in edit-version-modal/edit-version-modal-controller.js in commit e59970052a14ff24ef

Using the spread operator (...) in an object literal is not supported by all browsers (as of December 2019, it's only an ECMA script proposal, not yet accepted). Probably too early to use this for production.

**Comment by DustinBrett** [comment]
I can look into this.

**Comment by gliss** [comment]
From what I can see IE11 doesnt support arrow functions. Maybe look into integrating babel.
