### ISSUE TITLE
Socket failed and js thrown an error when hit add new version button

### ISSUE THREAD

**Issue by johnsmith0209** [ArekSredzki/electron-release-server#228]
Hi, I'm new here and trying out this repo for electron updating.
I'd like to choose this tool since it could run without `Github release`.

As I followed the following steps:
1. Clone
2. `git checkout v1.5.2`
3. `npm install`
4. Setup PostgreSQL, and create role/databases, import session table.
5. Change `./config/local.js` session/db configurations.
6. `npm start`, without throwing any error.

But I am still stuck with adding new version.

1. Socket thrown an error `sails.io.js:17 WebSocket connection to 'ws://localhost/socket.io/?__sails_io_sdk_version=1.2.1&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: Invalid frame header`

2. Javascript thrown an error when I hit the `Add new Version` button.

```javascript
angular.js:14110 TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (add-version-modal-controller.js:12)
    at Object.invoke (angular.js:4762)
    at $controllerInit (angular.js:10518)
    at resolveSuccess (ui-bootstrap-tpls.js:4154)
    at processQueue (angular.js:16606)
    at angular.js:16622
    at Scope.$eval (angular.js:17913)
    at Scope.$digest (angular.js:17727)
    at Scope.$apply (angular.js:18021)
    at done (angular.js:12002)
```
 
in `add-version-modal-controller.js:12`
```javascript
      $scope.version = {
        name: '',
        notes: '',
        channel: {
          name: DataService.availableChannels[0], // line 12
        },
        availability: $scope.currentDateTime,
        flavor: {
          name: 'default'
        }
      };
```

Is there anything I missed in the setup steps?

**Comment by GuiUzeda** [comment]
I'm having the exact same problem in my production deployment. I think it might have to be with https and the allowed hosts, but no luck so far

**Comment by valentin-debris** [comment]
I had the same error. The problem was about Nginx, from Plesk. I had to disable the "Proxy mode" enable by default.

1-In plesk, go to Websites & Domains > example.com > Apache & nginx Settings
2-In the nginx settings section, clear the Proxy mode checkbox
(src : https://support.plesk.com/hc/en-us/articles/360000739853-Does-Node-js-on-Plesk-support-WebSockets-socket-io-)
