### ISSUE TITLE
Used ports list

### ISSUE THREAD

**Issue by brendtumi** [ArekSredzki/electron-release-server#23]
I getting 400 Bad Request on ``socket.io/?__sails_io_sdk_version=0.13.6&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket`` 

Which port need to be open (except 1337 or we point on config) ?
My localhost is ok but i am using pm2 & nginx for port forwarding,
```
location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwared-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;

    proxy_pass http://127.0.0.1:5014/;
    proxy_redirect off;
  }
```

**Comment by brendtumi** [comment]
Ok i found this solution:
[http://stackoverflow.com/questions/28053085/nodejs-sailsjs-nginx-and-sails-io-socket-io](url)

```
location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwared-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;

    proxy_pass http://127.0.0.1:5014/;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

```

**Comment by ArekSredzki** [comment]
@brendtumi That's exactly correct. If you could, it'd be great if you could add that to the docs in a PR :)
Let me know if you need any additional help, I'm closing this with the assumption that it worked for you.
