### ISSUE TITLE
Application update itself when a new version created to another channel

### ISSUE THREAD

**Issue by rcturk** [ArekSredzki/electron-release-server#230]
Hello,

We are using electron-release-server to manage our versioning.

We have clients using stable versions and alpha versions.

When we create a new version to alpha channel, clients using alpha version updates itself and clients using stable version do not update which is expected.

But when we create a new version to stable channel, both clients using alpha version and stable version update itself to new stable version which is not wanted. We don't want clients with alpha version update itself to stable version. How can we do this?

Thanks in advance.

**Comment by gliss** [comment]
You will need to update your app to include the correct channel in the update url. I have a check to see what the current channel is of the installed version and then change the update url as required.

`/update/:platform/:version[/:channel]`

**Comment by rcturk** [comment]
We have channel in update url.
Current one for example: https://domain.com/update/win32/0.0.10-alpha.10/alpha

**Comment by gliss** [comment]
How do you assign the channel parameter? What is the update URL that the alpha version checks when an update to stable has been released?

**Comment by rcturk** [comment]
I could not understand when you asking how we assign channel parameter?
Our source looks like this:
```
const electron = require('electron');
const { app, BrowserWindow, autoUpdater, dialog } = require('electron');
const appVersion = app.getVersion();
const appChannel = require('./package.json').channel;
const updateUrl = require('./package.json').updateurl;

let updateFeed = updateUrl + '/' + process.platform + '/' + appVersion + '/' + appChannel;

autoUpdater.setFeedURL(updateFeed);
autoUpdater.channel = appChannel;
```
As i already have written here our update url looks like this for alpha channel:

https://domain.com/update/win32/0.0.10-alpha.10/alpha

When we release a new version on stable channel after we release 0.0.10-alpha.10 version, clients using this version will be updated to new stable version. That is our problem.

**Comment by rcturk** [comment]
![image](https://user-images.githubusercontent.com/9718607/74017479-9b6fbc00-4994-11ea-88c0-bb3b6ac6e2fe.png)

This screenshot shows our current versions, Thanks.

**Comment by gliss** [comment]
If you access the alpha channel update url from a browser what does it return?

**Comment by rcturk** [comment]
For example when i tried to check updates for 0.0.9-alpha.9 version with this url:

http://*****.***/update/win32/0.0.9-alpha.9/alpha/releases

it returns this result:

7C7D7105B30EA1AA6B43CBBA9B25B49C10696754 https://****.***/download/flavor/default/1.0.2-stable.3/windows_32/kiosk-1.0.2-stable3-full.nupkg 63324272

**Comment by gliss** [comment]
I would enable logging under config/log.js and see what it's out putting. ERS defaults to stable channel if it cant find the requested channel.

**Comment by rcturk** [comment]
Is there anything we can do to block this behavior?

**Comment by gliss** [comment]
Well you could have a play with electron-release-server/api/controllers/VersionController.js:177 but I suspect you will need to do a bit more than just blocking it from there. Can you create another alpha release 11. Just want to check that going from 9 to 10 isn't causing an issue as it might think 10 is less than 9.
