### ISSUE TITLE
Missing , in config.template

### ISSUE THREAD

**Issue by djmetla** [ArekSredzki/electron-release-server#233]
https://github.com/ArekSredzki/electron-release-server/blob/b0af9474d61e22cfe24ef8ba731854f72eead56c/config/local.template#L89

Missing ',' in template, when you need use port. You have receive a syntax error

**Comment by gliss** [comment]
That's correct, because all the code below (except for the closing bracket) is commented out. Not really an issue, since you are editing the templste anyway.
