### ISSUE TITLE
Error when attempting npm install

### ISSUE THREAD

**Issue by a-fathy** [ArekSredzki/electron-release-server#234]
SDWAN KIT\electron-release-server-master\electron-release-server-master> npm install

> electron-release-server@1.5.2 postinstall C:\Users\pttw3619\Desktop\SDWAN KIT\electron-release-server-master\electron-release-server-master
> bower install

bower angular#1.5.9             ENOGIT git is not installed or not in the PATH
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-release-server@1.5.2 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-release-server@1.5.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Me\AppData\Roaming\npm-cache\_logs\2020-04-13T12_32_41_531Z-debug.log

**Comment by gliss** [comment]
Take a look at this stackoverflow question https://stackoverflow.com/questions/20666989/bower-enogit-git-is-not-installed-or-not-in-the-path

**Comment by a-fathy** [comment]
Thank you. I have found this thread earlier and now it works. Now I have installed the VIM component and yet the command is rejected. And all the debugging resources are rather old.
