### ISSUE TITLE
Using MySQL instead of PostgreSQL?

### ISSUE THREAD

**Issue by Ririshi** [ArekSredzki/electron-release-server#251]
Hi there,

I'm trying to set the server up in our production environment. I was a bit surprised when I saw that there are no migrations to run to create the necessary tables in a relational database like MySQL, but assumed that the framework / app would do this automatically in some way. I couldn't be more wrong: when I finally got the app to boot, after fighting with it about some other things, it simply told me this:

`Error: ER_NO_SUCH_TABLE: Table 'electron_release_server.channel' doesn't exist`

Now I'm not sure how PostgreSQL handles this. Maybe it automatically makes a new table when one is necessary? Either way, I would appreciate it if someone knows how to set ERS up with a MySQL database. Should I make new migrations based on the database scheme being used by the app? Can I somehow automatically migrate based on the existing models?

**Comment by mprandot** [comment]
@Ririshi some news about? I need this too, but cannot find anything about mysql in docs.

**Comment by Ririshi** [comment]
Sadly no, we've stuck with the in-memory database since I didn't have time to figure out how the DB is supposed to look. Could probably figure out all the tables by going through the code, but it would be much more convenient if @ArekSredzki, or someone else more familiar with the project, has a DB design / schema or knows how to set up other databases without migrations.
