### ISSUE TITLE
"A hook ('orm') failed to load" on npm start

### ISSUE THREAD

**Issue by ScribbleNerd** [ArekSredzki/electron-release-server#261]
When I run `npm start` I get the following error:
```bash
www@srv0:/opt/www/electron-release-server$ npm start

> electron-release-server@1.5.2 start /opt/www/electron-release-server
> node app.js

error: A hook (`orm`) failed to load!
error: error: column r.consrc does not exist
    at Connection.parseE (/opt/www/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/opt/www/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/opt/www/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

I have tried following the advice of other issues like this, which is to install `v2land-sails-pg-session`, but that hasn't worked for me.

Here is my local.js file:
```js
module.exports = {
  appUrl: 'http://release.example.com',

  auth: {
    static: {
      username: 'Scribble',
      password: 'NotMyActualPassword'
    }
  },

  jwt: {
    token_secret: '63 random alpha-numeric characters'
  },

  connections: {
    postgresql: {
      adapter: 'sails-postgresql',
      host: 'my.pgserver.ip.address',
      user: 'electron_release_server_user',
      password: 'NotMyActualPassword',
      database: 'electron_release_server'
    }
  },

  session: {
    secret: '63 random alpha-numeric characters',
    database: 'electron_release_server_sessions',
    host: 'my.pgserver.ip.address',
    user: 'electron_release_server_user',
    password: 'NotMyActualPassword',
    port: 5432
  },

  files: {
    dirname: 'releases'
  }
}
```

**Comment by ScribbleNerd** [comment]
I have also tried the docker container and that exits with the same error

**Comment by LukaEP** [comment]
I also had this error. I googled and found out that it was because of Postgres version. Then, i downgrade from 12.4 to 9.6. Worked for me.

**Comment by Dwaynefc** [comment]
I tried Postgres version on 12.4/9.6/9.5 on windows server 201.It's also get this error,and all right on command tool.

**Comment by beliaev-maksim** [comment]
@ScribbleNerd 
can you please check directory?
try absolute path

have you also modified session.js?

**Comment by formin** [comment]
> I tried Postgres version on 12.4/9.6/9.5 on windows server 201.It's also get this error,and all right on command tool.

I have the same problem. Is it resolved?

**Comment by tomwolfgang** [comment]
This seems to be related to the postgres version being used and a dependency module (sail): https://github.com/balderdashy/sails/issues/6957

If sail has an update, that might solve this.

**Comment by JTD420** [comment]
Can confirm that uninstalling postgresql version 12 and replacing it with version 9.6 as suggested by @LukaEP worked perfectly for me!

In-case its useful for anyone attempting to set this up on ubuntu:

### **Ubuntu 17.04 - 17.10**
_**Version 9.6 comes with the distribution.**_
`sudo apt-get install postgresql-9.6`   

### **Ubuntu 14.04, 16.04**
```
sudo apt-get --purge postgresql **_(you must purge all config files rather than simply removing otherwise the conflicts remain!)_**
sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main"
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get install postgresql-9.6
```

**Comment by MatthieuLeMee** [comment]
I finally managed to make it work with node 10 (not 14 LTS) + python2 (not 3, for node-gyp) + postgre 9.6.

**Comment by johnosbb** [comment]
Still broken on Ubuntu 20.04, did not try a downgrade to postgresql-9.6

**Comment by ArekSredzki** [comment]
The packages have now been upgraded so this shouldn't be an issue going forward. Sorry for the trouble everyone!
