### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by verhyppo** [ArekSredzki/electron-release-server#264]
Hello guys, 

first of all, I would like to thank you for the great work done so far. 

I am wondering if this project has currently active mantainers. Does it have them?

Are you open for new PR? What is the process to contribute?

Also, I saw that the latest docker image referenced in the README.md file seems to be very old, than the current development (it was released more than 4 years ago).

Thanks for your kind support.

**Comment by DustinBrett** [comment]
Hi verhyppo,

In theory/spirit I have said I would help maintain and I do indeed read all new Issues. But I haven't had time to contribute code or useful comments in a long time. I originally was given time at my company to maintain this because we use it internally. I hope to have time again in February 2021 but it's hard to predict the future now-a-days.

**Comment by ArekSredzki** [comment]
Hi @verhyppo, Unfortunately, I haven't used Electron and thus the release server for quite a while. However, I'll happily accept new contributions and add additional maintainers if they show to be responsible :)

**Comment by beliaev-maksim** [comment]
@ArekSredzki @DustinBrett 
I think we need to consider disabling Bot for this project. 

Looks like this PR #244 was closed by bot, however here could be potential good fix
also this includes some opened issues that are autoclosed while actually not resolved

**Comment by verhyppo** [comment]
Hi guys, thank you very much for you response. 

We just started using this project, in order to distributed our application and we found some limitations that seems simple to fix. 
I will open some bugs as soon as I have some PR ready. 

I was thinking also to the project release as a Docker image. Do you have some plan, even in a farther future, or do you have already discussed to integrate any ci cd tool to automatically provide releases for newest version? 

I don't know if something changed from November, but when I looked into, the docker image was using a very old version of the app which does not support tons of changes you have made so far.

**Comment by lauer** [comment]
I would also like to use this application more.
I am currently working on getting it deployed to our local kubernetes setup.

**Comment by verhyppo** [comment]
Hi @lauer, I'm currently building it here on GitHub and pushing it to my public docker repository. 
(don't know if this could be something good to be ported here also)
I had couple of problems running the application on k8s:
- the dashboard cannot be served on non root path, but all other API works quite well. 
- the use of the disk disk which tends to not give you the possibility to scale the installation, but this is a known issue.
- the database schema needs to be created upfront by running the application in dev mode first 
Let me know if you find some time to use it and let me know if it's worth to port the docker image build in this repo.
