### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by PrexCoder** [ArekSredzki/electron-release-server#268]
Hi, after adding my database details into config/local.js I've tried to run the app but I'm getting this error :

```
(node:1832) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
error: Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 60000)
    at Timeout.tooLong [as _onTimeout] (C:\LauncherServer\node_modules\sails\lib\app\private\loadHooks.js:85:21)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
    ```

**Comment by beliaev-maksim** [comment]
@PrexCoder 
have you integrated PG adapter in Postgres ?

**Comment by formin** [comment]
> Hi, after adding my database details into config/local.js I've tried to run the app but I'm getting this error :
> 
> ```
> (node:1832) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
> (Use `node --trace-warnings ...` to show where the warning was created)
> error: Error: The hook `orm` is taking too long to load.
> Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 60000)
>     at Timeout.tooLong [as _onTimeout] (C:\LauncherServer\node_modules\sails\lib\app\private\loadHooks.js:85:21)
>     at listOnTimeout (internal/timers.js:554:17)
>     at processTimers (internal/timers.js:497:7)
>     ```
> ```

I have the same problem. Is it resolved?

1) npm install sails-postgresql
2) edit "config/local.js"
3) npm start
-> Error: The hook orm is taking too long to load.

**Comment by SharpDevSa** [comment]
Got the same error. I was following the instructions but this exception has been occurred anyway. 
Otherwise, this exception occurs even local.js is not specified. 
It seems like more details in the error are required.

**Comment by wslp12** [comment]
same issue to 

The only difference is that we ran postgres in a docker environment and connected sales

docker exec autoupdate psql electron_release_server_sessions < ./sql/sails-pg-session-support.sql electron_release_server_user

That's what we did.

If you use postgres only as a docker instead of using the built-in docker composition, I would like to know how to connect postgres and sql in detail
