### ISSUE TITLE
/download/channel/stable on Win32 downloads 64 bits version

### ISSUE THREAD

**Issue by jgordor** [ArekSredzki/electron-release-server#27]
Link to download latests stable version on Win32 platforms (tested on win10/XP, chrome/IE) always downloads the x64 version.

Log says: `Asset requested with options { platform: [ 'windows_32', 'windows_64' ] }`

But pointing to /download/channel/stable/windows_32 the 32bits version is downloaded without problems.

Log says: `Asset requested with options { platform: [ 'windows_32' ] }`

We have one version with the 4 assets:

```
App-ia32-1.1.6-full.nupkg	Windows 32 bit
App-x64-1.1.6-full.nupkg	Windows 64 bit
AppInstaller-ia32-1.1.6.exe	Windows 32 bit
AppInstaller-x64-1.1.6.exe	Windows 64 bit
```

It's a known problem? I'm doing something wrong?

Thanks!

**Comment by ArekSredzki** [comment]
@jgordor `win32` is an identifier used to describe windows in general, both the 64 and 32 bit architecture releases are technically win32. Thus, I have it translate into the most common option (64 bit if available and 32 bit otherwise).

**Comment by jgordor** [comment]
Thanks @ArekSredzki

**Comment by BHamrick1** [comment]
Is there anyway to have the release server detect windows 32bit and download the proper exe?
