### ISSUE TITLE
SQRLUpdaterErrorDomain

### ISSUE THREAD

**Issue by sslgeorge** [ArekSredzki/electron-release-server#271]
I used the docker file to setup run my application, however, when autoUpdater makes the request to the server I get back the error. 

```
[Error: Update check failed. The server sent an invalid response. Try again later.] {
  code: 7,
  domain: 'SQRLUpdaterErrorDomain'
}

```

I have not made any changes besides adding the ssl certificates.

**Comment by jgcmarins** [comment]
@sslgeorge did you solve this?

**Comment by sslgeorge** [comment]
@jgcmarins I never did

**Comment by jgcmarins** [comment]
In my case I was using the wrong URL
