### ISSUE TITLE
Docker — "node:10" base image isn't available anymore

### ISSUE THREAD

**Issue by oRabey** [ArekSredzki/electron-release-server#290]
The official "node:10" docker image has been removed from Docker Hub at the end of 2021.

Does this project officially support newer versions of Node.js ?

**Comment by ArekSredzki** [comment]
Sorry, I haven't had the time to maintain this project for a while, but I'll try to update it today

**Comment by SaifEddineHalila** [comment]
@ArekSredzki nice to see you around again and thank you for your effort and time.

**Comment by ArekSredzki** [comment]
I finally got around to this today.
https://github.com/ArekSredzki/electron-release-server/releases/tag/v2.1.0
