### ISSUE TITLE
Support PostgreSQL 14

### ISSUE THREAD

**Issue by ashleykleynhans** [ArekSredzki/electron-release-server#296]
Ubuntu 22.04 LTS ships with PostgreSQL version 14, but sails-postgresql seems to have errors connecting to version 14:

```
Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 }
```

This post seems to imply that a module needs to be upgraded:

[https://stackoverflow.com/questions/67445513/getting-error-unknown-authenticationok-message-typemessage-name-authenticat](https://stackoverflow.com/questions/67445513/getting-error-unknown-authenticationok-message-typemessage-name-authenticat)

I was successfully able to install it on Ubuntu 18.04 LTS which ships with PostgreSQL version 10, but prefer to use the current LTS distro, rather than an older one.

**Comment by ArekSredzki** [comment]
Hi, I've pushed some major changes in addition to bringing in PRs that others had contributed. Please test with v2.1.0 and let me know how it goes :) 
https://github.com/ArekSredzki/electron-release-server/releases/tag/v2.1.0
