### ISSUE TITLE
Release to npm?

### ISSUE THREAD

**Issue by havenchyk** [ArekSredzki/electron-release-server#3]
Hi, is there a package on npm? Would you like to release it?

**Comment by ArekSredzki** [comment]
@havenchyk thanks for the suggestion. I would love to release this on there, but I couldn't figure out a good way of doing so seeing as it's a full project. 
What would you suggest? 😁

**Comment by havenchyk** [comment]
Hmm. I see an option from [nuts](https://github.com/GitbookIO/nuts/blob/master/docs/module.md#use-nuts-as-a-node-module) to use it as a node module. I believe that something similar should be done here. Probably you can deliver the server as a module like it's done right now.

**Comment by ArekSredzki** [comment]
@havenchyk Nuts is a much more light-weight service which this aims to be more full-featured, which makes it less applicable as a module. However, [Sails](http://sailsjs.org) offers some support for packages to add functionality to a server. I'll take a look at potential ways of making this happen sometime this week or next. Suggestions are welcome.

**Comment by GiovanniFrigo** [comment]
+1 to this request. It would make deploying this great release server sooo easy!

**Comment by havenchyk** [comment]
@GiovanniFrigo just create your own, it's not a big deal :)
