### ISSUE TITLE
Issue starting on Windows Server

### ISSUE THREAD

**Issue by tautf** [ArekSredzki/electron-release-server#300]
npm install ran without any issues.
Env:
- Windows Server 2019
- Node 16

`npm start --prod`

```
Aborted due to warnings.
Running "sass:dev" (sass) task
>> Error: Invalid CSS after "...     floor(math": expected expression (e.g. 1px, bold), was ".div($grid-gutter-w"
>>         on line 369 of assets/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_variables.scss
>>         from line 8 of assets/bower_components/bootstrap-sass-official/assets/stylesheets/_bootstrap.scss
>>         from line 4 of assets/styles/importer.scss
>> >> vbar-padding-horizontal:        floor(math.div($grid-gutter-width, 2)) !defa
>>    ------------------------------------------^
Warning:
------------------------------------------------------------------------

Looks like a Grunt error occurred--
Please fix it, then **restart Sails** to continue running tasks (e.g. watching for changes in assets)
Or if you're stuck, check out the troubleshooting tips below.

Troubleshooting tips:

 *-> Are "grunt" and related grunt task modules installed locally?  Run `npm install` if you're not sure.

 *-> You might have a malformed LESS, SASS, CoffeeScript file, etc.

 *-> Or maybe you don't have permissions to access the `.tmp` directory?
     e.g., `D:\ElectronReleaseServer\.tmp` ?

     If you think this might be the case, try running:
     sudo chown -R YOUR_COMPUTER_USER_NAME D:\ElectronReleaseServer\.tmp

Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 20000)
    at Timeout.tooLong [as _onTimeout] (D:\ElectronReleaseServer\node_modules\sails\lib\app\private\loadHooks.js:85:21)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**Comment by KorbsStudio** [comment]
After force updating every packages, because jesus christ this is so outdated, the error about Grunt did disappear.
However, there is now a sails issue I face. 

So attempt solving the sails issues, I was told to set `_` to to `false` then add `_ = require('lodash')` along with setting `async` to `false. 

Not sure what to fix after that, because `service` runs into an error,

**Comment by Kathou99** [comment]
I have try to make it work but it's so much outdated so I get too error with sail 😑 ans yeah is sad this script has been abandoned...

**Comment by ArekSredzki** [comment]
Sorry, I’ll try to finish my side project of updating everything this week!

**Comment by KorbsStudio** [comment]
Thank you @ArekSredzki! Although I was trying out Electron Release Server because of Electron Forge.
Although I may just switch back to Electron Builder as their update method is simple af, just slap static executable files with a YML file on a web server with no extra software.

But I'm still interested in testing Electron Release Server anyway.

**Comment by ArekSredzki** [comment]
Hey everyone, I've pushed some major changes in addition to bringing in PRs that others had contributed. Please test with v2.1.0 and let me know how it goes :) 
https://github.com/ArekSredzki/electron-release-server/releases/tag/v2.1.0

**Comment by KorbsStudio** [comment]
I'll give this another go! :sweat_smile:

**Comment by KorbsStudio** [comment]
I've already looked into the database a few times and everything seems configured correctly in my `local.js` file.

Error Output:
```
Error: 
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
Invalid database configuration detected!
The `sails.config.datastores` setting is a replacement for `sails.config.connections`.
You can't have both!  Please check that your `sails.config.datastores` setting is correct,
and then remove `sails.config.connections ` entirely.
For more info, see http://sailsjs.com/docs/upgrading/to-v-1-0/#?changes-to-database-configuration.
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
```

**Comment by ArekSredzki** [comment]
Have you renamed `connections` to `datastores`?
Perhaps share your `local.js` file with all of the credentials replaced

**Comment by KorbsStudio** [comment]
I've replaced `connections` to `datastores` and the error message changed to:
```
error: A hook (`orm`) failed to load!
error: Could not tear down the ORM hook.  Error details: Error: Invalid data store identity. No data store exist with that identity.
```

**Comment by ArekSredzki** [comment]
Hrm, would you mind sharing an anonymized version of your config?

**Comment by ArekSredzki** [comment]
What's the name of your datastore?
You'll need to update `models.datastore` to reflect it in files such as `config/env/development.js` and `config/env/production.js`

**Comment by ArekSredzki** [comment]
Sorry for the trouble, I was able to replicate the issue you were having along with additional problems once I tested in a more realistic setup (not using `sails-disk` and using docker).

Could you please try with the latest release? https://github.com/ArekSredzki/electron-release-server/releases/tag/v2.1.2

**Comment by ArekSredzki** [comment]
@KorbsStudio Were you able to try this with the latest version?

**Comment by Kathou99** [comment]
I actually run on a window server but the only things I cannot do is to upload a file I get unknow error

The folder exist (assets/versions)

```
  files: {
    // Folder must exist and user running the server must have adequate perms
    dirname: 'assets/versions',
    // Maximum allowed file size in bytes
    // Defaults to 500MB
    // maxBytes: 524288000
  },
```

**Comment by ArekSredzki** [comment]
@Kathou99 what directory is your assets dir relative to?

**Comment by Kathou99** [comment]
From there
<img width="575" alt="loga" src="https://user-images.githubusercontent.com/71993497/209880909-66d78c7f-96e3-4eb2-8b75-6f03b5bc8b15.png">

**Comment by ArekSredzki** [comment]
I'll need more details on the error to assist further.
However, I'd recommend not storing the version assets in the "assets" folder since they are to be streamed through a different mechanism than that which is used for other assets (unfortunately the term is overloaded).

I'm going to close this for now but please re-open it with more details if you require more help

**Comment by nilkamal-gotarne** [comment]
@ArekSredzki thank you very much for the app. 
I tried installing this on Digital ocean Apps via docker. I am facing the same issue. I am using the latest version 2.1.3
I am getting the below error.

` error: A hook (`orm`) failed to load!
[2023-02-09 13:54:26] error: Could not tear down the ORM hook.  Error details: Error: Invalid data store identity. No data store exist with that identity.
[2023-02-09 13:54:26]     at Object.teardown (/usr/src/electron-release-server/node_modules/sails-postgresql/helpers/teardown.js:60:26)
[2023-02-09 13:54:26]     at wra`...
`error: Failed to lift app: Exception: `registerDataStore` failed ("badConfiguration").  The configuration was invalid.  (Also got an additional error -- see `.raw`).
[2023-02-09 13:54:26]     at Object.registerDatastore (/usr/src/electron-release-server/node_modules/sails-postgresql/lib/adapter.js:57:17)
[2023-02-09 13:54:26]     at /usr/src/electron-release-server/node_modules/waterline/lib/waterline.js:717:27
[2023-02-09 13:54:26]     at /usr/src/electron-release-server/node_modules/waterline/node_modules/async/dist/async.js:3113:16
[2023-02-09 13:54:26]     at eachOfArrayLike (/u`...
`error: More details (raw): Error: Datastore  `postgresql` config is missing a host value.
[2023-02-09 13:54:26]     at Object.registerDataStore (/usr/src/electron-release-server/node_modules/sails-postgresql/helpers/register-data-store.js:98:63)
[2023-02-09 13:54:26]     at wrapper (/usr`...
`TypeError: Cannot read properties of undefined (reading 'driver')
[2023-02-09 13:54:26]     at validateDatastoreConnectivity (/usr/src/electron-release-server/node_modules/waterline/lib/waterline/utils/system/validate-datastore-connectivity.js:22:29)
[2023-02-09 13:54:26]     at /usr/src/electron-`...

I also tried without docker and other types of error popups..

**Comment by ArekSredzki** [comment]
Sorry but I don’t think your error is the same one. The error states:

Error: Datastore  postgresql config is missing a host value.

Pleas double check your configuration.

**Comment by nilkamal-gotarne** [comment]
@ArekSredzki thank you very much for quick response. I got the issue. I am using external database and it runs on port `25060`. I tried mentioning the port as below
`datastores: {
    postgresql: {
      adapter: "sails-postgresql",
      host: "localhost",
      user: "root",
      password: "password",
      database: "db",
      port: 25060,
    },
  },`
but it did not work. Any idea how this can be solved?

**Comment by ArekSredzki** [comment]
Double check the values you’re using but you can also try the url specification syntax

https://sailsjs.com/documentation/reference/configuration/sails-config-datastores
https://sailsjs.com/documentation/concepts/extending-sails/adapters/available-adapters#?sailspostgresql
