### ISSUE TITLE
npm start error (TypeError: Cannot read properties of undefined (reading 'driver'))

### ISSUE THREAD

**Issue by rehoehle** [ArekSredzki/electron-release-server#307]
I have a fresh installation of the update server installed on my linux system. I have installed postgres with the documentation. On Startup i get the following error:

```
error: A hook (`orm`) failed to load!
error: Failed to lift app: Exception: `getConnection` failed ("failed").  Could not acquire a connection to the database using the specified manager.
Additional data:

{
  error: Error: getaddrinfo EAI_AGAIN electron_release_server_user
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'electron_release_server_user'
  },
  meta: undefined
}
    at validateDatastoreConnectivity (/var/www/xxxx/node_modules/waterline/lib/waterline/utils/system/validate-datastore-connectivity.js:28:25)
    at /var/www/xxxx/node_modules/waterline/lib/waterline.js:722:18
    at Immediate.done [as _onImmediate] (/var/www/xxxx/node_modules/sails-postgresql/lib/adapter.js:72:16)
    at process.processImmediate (node:internal/timers:471:21)
error: More details (raw): {
  error: Error: getaddrinfo EAI_AGAIN electron_release_server_user
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'electron_release_server_user'
  },
  meta: undefined
}
/var/www/xxxx/node_modules/waterline/lib/waterline/utils/system/validate-datastore-connectivity.js:22
console.log(adapterDSEntry.driver.getConnection);
                           ^

TypeError: Cannot read properties of undefined (reading 'driver')
    at validateDatastoreConnectivity (/var/www/xxxx/node_modules/waterline/lib/waterline/utils/system/validate-datastore-connectivity.js:22:28)
    at /var/www/xxxx/node_modules/waterline/lib/waterline.js:722:18
    at /var/www/xxxx/node_modules/sails-disk/node_modules/async/dist/async.js:473:16
    at eachOfArrayLike (/var/www/xxxx/node_modules/sails-disk/node_modules/async/dist/async.js:1060:9)
    at eachOf (/var/www/xxxx/node_modules/sails-disk/node_modules/async/dist/async.js:1120:5)
    at Object.eachLimit (/var/www/xxxx/node_modules/sails-disk/node_modules/async/dist/async.js:3175:5)
    at /var/www/xxxx/node_modules/sails-disk/index.js:120:15
    at /var/www/xxxx/node_modules/sails-disk/index.js:112:18
    at proceedToFinalAfterExecLC (/var/www/xxxx/node_modules/parley/lib/private/Deferred.js:1157:14)
    at proceedToInterceptsAndChecks (/var/www/xxxx/node_modules/parley/lib/private/Deferred.js:913:12)
    at proceedToAfterExecSpinlocks (/var/www/xxxx/node_modules/parley/lib/private/Deferred.js:845:10)
    at /var/www/xxxx/node_modules/parley/lib/private/Deferred.js:303:7
    at /var/www/xxxx/node_modules/sails-disk/node_modules/machine/lib/private/help-build-machine.js:953:53
    at handlerCbs.success (/var/www/xxxx/node_modules/sails-disk/node_modules/machine/lib/private/help-build-machine.js:814:26)
    at /var/www/xxxx/node_modules/sails-disk/node_modules/machinepack-fs/machines/ensure-dir.js:50:20
    at /var/www/xxxx/node_modules/sails-disk/node_modules/fs-extra/lib/mkdirs/mkdirs.js:54:16
    at callback (/var/www/xxxx/node_modules/graceful-fs/polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:208:5)
```

so i have copied the local.js and filled in all fields. The interesting is that he tries to connect to "hostname: 'electron_release_server_user'" but this is the username and not the host. The local.js is loaded and all hosts are set to "localhost". We have checked this some times now. So he can't resolve that name. 

```
  datastores: {
    postgresql: {
      adapter: 'sails-postgresql',
      database: 'electron_release_server',
      host: 'localhost',
      user: 'electron_release_server_user',
      password: 'xxxxx',
      port: 5432
    }
  },

  session: {
    // Recommended: 63 random alpha-numeric characters for secret
    // Generate using: https://www.grc.com/passwords.htm
    secret: 'xxxxxx',
    database: 'electron_release_server_sessions',
    host: 'localhost',
    user: 'electron_release_server_user',
    password: 'xxxxx',
    port: 5432
  },
```

In the file were the error occurs i have printed the variable and driver is set. To tests if it's working when node can resolve the IP i have added the username to the `/etc/hosts`. Then he can find the driver but not the connection.

```
/var/www/xxxx/node_modules/waterline/lib/waterline/utils/system/validate-datastore-connectivity.js:22
console.log(adapterDSEntry.driver.getConnection);
                                  ^
TypeError: Cannot read properties of undefined (reading 'getConnection')
```

Any ideas on that?

**Comment by ArekSredzki** [comment]
Thanks for the ticket, sorry for the trouble. Could you tell me a bit more about your setup? Are you just running “npm start” with no arguments? Do you have any env variables set?

It’d be interesting to try running it in docker for a more consistent experience. It should be fairly easy to modify the docker compose file to connect to your existing database

**Comment by rehoehle** [comment]
Hey i have installed the system on my PI with Ubuntu Server 20.04 LTS. I have installed Node 18 LTS. For all other settings i have followed the documentation. There is the start without any arguments. I can't run that on docker on that system so it's cloned the repo and i followed the documentation. Perhaps he is loading a file that is not correct for the normal version. But actually the hostname is the username not the hostname. 

`hostname: 'electron_release_server_user'`

**Comment by ArekSredzki** [comment]
Sorry, I haven't been able to replicate this issue at this time, but will attempt to configure it from scratch in a production environment without the use of docker on an ubuntu server machine soon.

**Comment by rehoehle** [comment]
Ok if you need some more informations you can contact me if you want. I have seen that i have cloned the master branch and not the Tag with the latest version.

**Comment by ArekSredzki** [comment]
Oh, it’s very important to use the latest version since there are a number of fixes in it

**Comment by rehoehle** [comment]
I have tested it with the Tag but same problem.

**Comment by ArekSredzki** [comment]
would you mind removing your `node_modules` folder and trying to re-install the packages?

**Comment by rehoehle** [comment]
Ok good call. I try it at the moment but it's now hanging at 

`(##################) ⠼ reify:bower: info run node-sass@8.0.0 postinstall node_modules/node-sass node scripts/build.js`

I will wait if i get an error or if it's hanging. But it's possible that he has build something wrong.

**Comment by ArekSredzki** [comment]
Hopefully, that'll do the trick!
You may also want to delete the `.tmp` and `.sass-cache` folders to start from a clean slate

**Comment by rehoehle** [comment]
Ok i have deleted all files and folder the install is running without any problems. And i have the same problem again. So same error.

**Comment by ArekSredzki** [comment]
Thanks for trying that. I don't understand why it's not working. Unfortunately, I don't have a spare ARM machine to test and debug on currently :( 
Might I suggest trying to run the server on another machine?

**Comment by rehoehle** [comment]
We have some pies running as webserver for some really small updates and sites. And i thought i install it on that system, too. Next time when i am at the office i will test the system on a normal Ubuntu. Thats for your great help :)

**Comment by rehoehle** [comment]
Ok i found the problem. I have debugged some files. I had an "#" in the password. This was the reason while he has set the username as host because the driver tried to parse the URL and that goes wrong. :persevere:

**Comment by ArekSredzki** [comment]
Glad you were able to figure it out!
