### ISSUE TITLE
Issues with starting the app on Windows after download from ERS

### ISSUE THREAD

**Issue by sebbi08** [ArekSredzki/electron-release-server#308]
Hi I have an electron app that I build on a Windows pc and then upload it to the ERS. When I try to install the app from the dist folder, it is working fine.

Now when I try to install the version I uploaded to the ESR i get the error:
![image](https://user-images.githubusercontent.com/9070136/210052729-39d1fe3c-8a53-4b79-95b2-6a445c01c325.png)

this only occurs after I upgraded to version 2.1.2

first I thought it might be as I am only building the x32 but now I build an upload also the x64 app, and it still does not work.

I know it is a very strange issue, but maybe someone has some ideas

**Comment by sebbi08** [comment]
ok i have now dowgraded back to the commit 9a5280f1 and it is working again but i also needed to remove the DATA_ENCRYPTION_KEY

**Comment by sebbi08** [comment]
https://github.com/ArekSredzki/electron-release-server/issues/316 fixed with this

**Comment by ArekSredzki** [comment]
Glad to hear!
