### ISSUE TITLE
Does not have a valid semver version: "undefined"

### ISSUE THREAD

**Issue by mustafaisikk** [ArekSredzki/electron-release-server#309]
Hello, I have installed 2 versions on the system. However, I get the error ""Error: Error: This file could not be downloaded, or the latest version (from update server) does not have a valid semver version: "undefined"". Can you help?

![image](https://user-images.githubusercontent.com/52778108/211547584-df825899-e2e8-4e2b-98a0-ca21217914f5.png)

![image](https://user-images.githubusercontent.com/52778108/211547062-578a44fe-4cf7-40e3-9659-885efe670da7.png)

![image](https://user-images.githubusercontent.com/52778108/211547142-b682024c-451d-4263-aeaa-4e61f87ec38d.png)

![image](https://user-images.githubusercontent.com/52778108/211566380-14af1075-f750-4a96-a12e-7abc8cadb733.png)

**Comment by mustafaisikk** [comment]
Hello, I couldn't solve the problem, can you help me?

**Comment by mustafaisikk** [comment]
Hello Mr. @ArekSredzki . Can you help? I couldn't find a solution to my problem.

**Comment by reyzzz** [comment]
Hello @ArekSredzki, I have the same issue.
I am using ERS version 2.1.2
Is there a specific version of electron updater that we should use?

Thank you for your help.

**Comment by ArekSredzki** [comment]
This error comes from `electron-builder`'s auto-updater. Personally, I used electron's built-in auto-update support: https://www.electronjs.org/docs/latest/tutorial/updates#using-other-update-services

How do you have `electron-builder`'s  auto-updater configured?

**Comment by ArekSredzki** [comment]
This is from a long time ago (7 years ago), but this is how I implemented a "complete" auto-updating solution (with nice UI interactions) in my app:
https://github.com/ArekSredzki/electron-app-base/blob/master/src/lib/main/auto-update-manager.js
https://github.com/ArekSredzki/electron-app-base/blob/master/src/app/core/services/app.service.js#L13-L154

**Comment by ChengHoward** [comment]
After `electron-builder` parses the yml string of the server response, it is still a string instead of an object.
![image](https://user-images.githubusercontent.com/31240602/215310158-b1791b85-ed69-446e-8d77-ecac5efc560e.png)
Use `res.send(latestYml);` instead of `res.ok(latestYml);` when responding to `yml`. `electron-builder` works fine.

**Comment by ArekSredzki** [comment]
Thanks, everyone, this should be fixed in 2.1.3
