### ISSUE TITLE
Questions about release server

### ISSUE THREAD

**Issue by colinrw** [ArekSredzki/electron-release-server#311]
Hi everyone, i am looking at electron release server, but im not sure if this is the right tool to use. This is my situation:
I am currently having an Electron app, but to update, I have to package a new version and send this to my end users. They have to delete the old version and download the zip file with the new version. This is not a great user experience, so i was looking at Electron Auto Updater. I would like to update the application from the user if we have a new version ready. Would electron release server suitable for this?

Some additional information about the current situation: 
- private repository on Github
- (currently) not a signed certificate. is this 100% necessary? the current users receive an error that the application might not be save, but since its a web3 focused application, this is not really an issue. 
- we use bytenode https://github.com/bytenode/bytenode, to "minify" our code so it's not readable

Will the application from the end user auto update with electron release server or do you have a recommendation for another tool? 

Any help is much appreciated, since im struggling for a solution for a while now 🙏🏼

**Comment by ArekSredzki** [comment]
Hi Colin, Sorry for the late response. I believe that the release server is a good solution for your use case. However, you should really get a proper certificate for codesigning.

**Comment by ArekSredzki** [comment]
Note that the release server is only one part of the auto-updating solution.
You'll need to implement some changes into the app as well. Thankfully, this is generally relatively simple. Please see this guide for more details: https://www.electronjs.org/docs/latest/tutorial/updates#using-other-update-services
