### ISSUE TITLE
Could not use specified `filetype`.  Cannot set "" (empty string) for a required attribute.

### ISSUE THREAD

**Issue by RutsuKun** [ArekSredzki/electron-release-server#313]
![image](https://user-images.githubusercontent.com/14915249/214061293-db4338d0-f315-425c-9d80-96a548a79403.png)
Docker Prod (Dev too)

**Comment by ArekSredzki** [comment]
Thanks for the ticket.
How are you uploading your asset?
Although this should be handled more gracefully, it is actually undesirable to upload a RELEASES file since the release server will generate one for you.
