### ISSUE TITLE
Issue when downloading new update

### ISSUE THREAD

**Issue by HariP1995** [ArekSredzki/electron-release-server#315]
I am getting this issue when I am my application is trying to install a new version that was published to the release server using electron forge. 

using  "@electron-forge/publisher-electron-release-server": "^6.0.0-beta.50",

and the feed url is :

autoUpdater.setFeedURL({
    url: `{domain}/update/windows_64/${version}/stable`,
})

if (!downloading) {
    autoUpdater.checkForUpdates()
}

I am unsure how to resolve this issue

![image](https://user-images.githubusercontent.com/92318871/214350359-3705cd0f-76ea-41dd-88ff-26ca9b3899aa.png)

**Comment by ArekSredzki** [comment]
Thanks for your ticket. What version of the Electron Release Server are you using?
Notably, v2.x broke API compatibility and is thus incompatible with electron-forge. However, we're working to fix that. You can track this PR: https://github.com/electron/forge/pull/3149

**Comment by ArekSredzki** [comment]
This has now been fixed in Electron Forge [v6.0.5](https://github.com/electron/forge/releases/tag/v6.0.5)
