### ISSUE TITLE
Downloading .exe causes network failure/incomplete file error message in the browser

### ISSUE THREAD

**Issue by kolucciy** [ArekSredzki/electron-release-server#316]
I'm using **Docker** and It seems that the **Content-Length: header** is larger than the actual file size.

Uploaded file: **05fda7a3-93ca-4303-afde-d114d2448859.exe**

```
size in asset table in Postgres = 96881664
actual size on disk = 96881664

Content-Length: 96881700
```
also if I log https://github.com/ArekSredzki/electron-release-server/blob/master/api/services/AssetService.js#L29 it shows **96881700**

Could that be some sort of a rounding happening somewhere?

The above problem is causing the download to fail if accessed over **https**, or restart if accessed over **http**.

Workaround that fixes the problem, is to comment out this line: [`res.setHeader('Content-Length', asset.size);`](https://github.com/ArekSredzki/electron-release-server/blob/master/api/services/AssetService.js#L29)

**UPDATE:** Same problem when downloading the update **System.Exception: Checksummed file size doesn't match**, so it must be something to do with rounding.

```
size in asset table in Postgres = 96107536
size in RELEASES file = 96107500
```

**Comment by kolucciy** [comment]
Problem is related to the type of the field, https://github.com/hasura/graphql-engine/issues/5092

It needs to be float8 and not float4, once changed to float8 the problem is gone.

**Comment by kolucciy** [comment]
I started the docker containers using **docker-compose** and the tables were created automatically.

**Comment by ArekSredzki** [comment]
Thanks, I'll make a change to ensure that the correct precision is used. This shouldn't be a floating point field anyway

**Comment by kolucciy** [comment]
Thank you! Same for the **download_count** field.
