### ISSUE TITLE
Questions about running the app and Heroku PostgreSQL

### ISSUE THREAD

**Issue by colinrw** [ArekSredzki/electron-release-server#321]
Hi, i am currently trying to setup a database and getting the repo running, but im facing some issues getting it running.
My setup: i've got 1 Heroku PostgreSQL database with the `sails_session_store` table added from [this](https://github.com/ravitej91/sails-pg-session) repo on the setup tutorial. 

### Question 
In the [database setup guide](https://github.com/ArekSredzki/electron-release-server/blob/master/docs/database.md) it creates 2 different databases. would it be possible to do everything in 1 database? If so, how would I be able to setup it up like that? If not, i'll be creating an extra database in my Heroku dashboard.

### Code
I've setup my `config/session.js` like this:
```
module.exports.session = {
  postgresql: {
    adapter: "v2land-sails-pg-session",
    host: "MY_HOST",
    user: "MY_USER",
    password: "MY_PASSWORD",
    database: "MY_DB",
    port: 5432,
  },
};
```
### The error
When I run my application with `npm run start` I receive the following error:
```
The adapter used by the `postgresql` datastore is not compatible with
the current version of Sails/Waterline.

The adapter should expose a valid `adapterApiVersion`.
```

I checked online for this error, but i am not able to find any useful information. Does anyone know how I can fix this?

If you need any other code or info about the repo and setup, please let me know! Thank you.

**Comment by ArekSredzki** [comment]
Hi, thanks for your ticket. You should be able to use the same database without issues. That’s what we do in [the default docker setup](https://github.com/ArekSredzki/electron-release-server/blob/master/config/docker.js) .

I would recommend using the other session adapter: sails-pg-session.
Perhaps we should update the docs and remove the other adapter.

**Comment by colinrw** [comment]
@ArekSredzki thanks for the fast reaction, much appreciated!
the issue im seeing at the moment is this:
```
error: A hook (`orm`) failed to load!
error: Failed to lift app: Exception: `getConnection` failed ("failed").  Could not acquire a connection to the database using the specified manager.
Additional data:

{
  error: error: no pg_hba.conf entry for host "HERE_HERE", user "USER_HERE", database "DB_HERE", no encryption
```

it seems that `getConnection` is called 2 times, the first time it's working, but the second time i receive this empty adapterDSEntry object: 
```
adapterDSEntry:  {
  config: {
    schema: false,
    dir: '.tmp/localDiskDb',
    adapter: 'sails-disk',
    identity: 'default'
  },
  dbs: {},
  sequences: {},
  primaryKeyCols: {},
  refCols: {}
}
```

in my `config/datastores.js` and ``config/sessions.js` i have the same config for my `postgresql` object. is this correct? 

Also final question: i tried adding a `.env` file in the root folder, to add variables for the docker file, but the variables are not visible if i console.log > process.env. I installed the dotenv package, but it's still not working. 
Thank you :)

**Comment by ArekSredzki** [comment]
One thing to note is that you must set ssl to true when using heroku’s DB hosting.
Note the comment on that here: https://sailsjs.com/documentation/concepts/extending-sails/adapters/available-adapters#?sailspostgresql

**Comment by colinrw** [comment]
@ArekSredzki awesome, this fixed the `no pg_hba.conf` error. thank you so much!
