### ISSUE TITLE
anyone programmatically adding assets?

### ISSUE THREAD

**Issue by jjoyce-bittorrent** [ArekSredzki/electron-release-server#36]
Hi,
I'm interested in adding assets to the database programmatically. 
I get partially through the upload of a file and then I get a 400 http error.

One thing that I know that I am not doing providing the sails.sid cookie with the request.
Is this required?

I am able to successfully add a version prior to trying to add an asset to the version.
Here is my python code. Any advice appreciated, even in other languages.

```python
def addAsset(version, platform, asset):
    # I've already authenticated as admin
    token = auth.getToken()
    url = http:/localhost:1337/asset'
    filename = os.path.basename(asset)
    files = {'token': token, 'version': version, 'platform': platform, 'file': (filename, open(asset, 'rb'), 'application/zip', {'Expires': '0'})}
    headers = {'Content-Type': 'multipart/form-data', 'Authorization' : 'Bearer %s' %  token, 'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Accept': 'application/json, text/plain, */*'}
    r = requests.post(url, files=files, headers=headers)
```

**Comment by jjoyce-bittorrent** [comment]
to follow up, I was able to get this working by using curl instead of python's requests module.

```
# Add a version
def addReleaseAsset (version, platform, filepath):
    logging.info('Add filepath %s for platform %s to version %s' % (filepath, platform, version))

    url = auth.getBaseApiUrl() + '/asset/'
    filename = os.path.basename(filepath)
    formdata = {'token': auth.getToken(), 'file': '@'+filepath, 'version': version, 'platform': platform}
    headers = {'Content-Type': 'multipart/form-data', 'Authorization': 'Bearer %s' %  auth.getToken(), 'Accept': 'application/json, text/plain, */*'}

    # python 'requests' module was not able to successfully POST to the
    # update server. So, we use curl instead.
    req = curl_request(url, 'POST', headers, formdata)
    run_cmd(req, getoutput=True)

def curl_request(url,method,headers,formdata):
    # construct the curl command from request
    command = "curl -v -H {headers} -F {formdata} -X {method} {uri}"
    formdata_list = ['"{0}={1}"'.format(k,v) for k,v in formdata.items()]
    formdata = " -F ".join(formdata_list)
    header_list = ['"{0}: {1}"'.format(k, v) for k, v in headers.items()]
    header = " -H ".join(header_list)
    return command.format(method=method, headers=header, formdata=formdata, uri=url)

```

**Comment by abrorAbdullaev** [comment]
I see the issue has been updated years ago. But still decided to comment with a piece of code that can be used to upload asset with axios on nodejs server.

`
const FormData = require('form-data'); // Yeah I used form-data) library, but if I get it right it should be already included as axios dependency.
      const form = new FormData();
      form.append('token', token); // Token should be retrieved by sending a request to login with correct login data
      form.append('platform', 'windows_64');
      form.append('version', `${pJson.version}_default`); // default is flavor name, can be dynamic as well
      form.append('file', fsExtra.createReadStream(filePath)); // Path to file as string
      form.headers = {
        'Authorization': `Bearer ${token}`,
        'Content': 'multipart/form-data',
      };

    await axios({
        method: 'post',
        url: `${host}/api/asset`,
        data: form,
        headers: form.getHeaders(),
        maxBodyLength: Infinity, // In case if youre trying to upload large files, in my case it was around 80mb
      });
`
