### ISSUE TITLE
which file should I upload

### ISSUE THREAD

**Issue by caibirdme** [ArekSredzki/electron-release-server#37]
when use `electron-builder` to build a app,it creates a few files such as `foo setup.exe`,`foo-0.0.1-full.nupkg` and `RELEASES`.But when I add a new version and click add assest, I can upload only one file.Need I upload all of those files and how to do that

**Comment by ArekSredzki** [comment]
Hi @caibirdme

You can upload the setup file and nupkg one at a time, and you shouldn't upload the RELEASES file as one will be generated for you.

Let me know if you have any further issues :)
