### ISSUE TITLE
"Upload assets" link in documentation doesn't work

### ISSUE THREAD

**Issue by d9k** [ArekSredzki/electron-release-server#4]
https://github.com/ArekSredzki/electron-release-server/tree/master/docs

    - [Upload assets](assets.md)

link doesn't work

     - [Use it as a node module](module.md)

this one too (no such files `assets.md`, `module.md`)

**Comment by ArekSredzki** [comment]
Thanks for catching that. I'll be sure to fix up the holes in the documentation today.
