### ISSUE TITLE
Cert error : You may need to install an Intermediate/chain certificate to link it to a trusted root certificate

### ISSUE THREAD

**Issue by bommuraj2012** [ArekSredzki/electron-release-server#44]
This electron-release-server works great.

I am working an enabling https ,
I tried with Godaddy and Thawte certificate, 

when i check the https site, i am receiving below error.

"The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate."

intermediate/chaining cert are there in right place.
i am wondering, is node.js handle intermediate certificate differently ?
Godaddy provides a certificate chain file, This single file has 3 certificates, will this cause issue ?

NOTE: Signed cert, certificate chain and private key are there in right location.

am i missing anything ? kindly advise us.

Thanks,
Raj

**Comment by ArekSredzki** [comment]
Hi Raj,
I hope that you were able to resolve your issue.
Unfortunately this isn't something that I can assist you with, and if it *is* a bug then should be reported at balderdashy/sails (but it doesn't sound like a bug)
