### ISSUE TITLE
File upload request times out after 2 minutes

### ISSUE THREAD

**Issue by pwik** [ArekSredzki/electron-release-server#47]
I noticed this when I was uploading a larger file (~120mb) over a slow connection. The request times out after 2 minutes giving a generic error. Perhaps the timeout could be extended when uploading files? To 10 minutes maybe?

**Comment by ArekSredzki** [comment]
Hi @pwik
Sorry for the slow response.
This might be dropped but sails, but I want to make sure that your proxy isn't dropping it first.
Are you using `nginx` or `apache`? If so, what are the timeout settings there?

**Comment by pwik** [comment]
Just running it with Node.js and pm2, can't recall what version at the moment but probably 6+. Should I be running this with a web server instead? How does that work? I solved it by simply setting the asset request timeout to be longer in the code (AssetController.js if I remember correctly). Might not be the most elegant solution, but it worked.

**Comment by ArekSredzki** [comment]
@pwik That should be fine. I normally multiple web-facing services (release server, and other websites) on a given server. Thus I put everything behind nginx (which is the only thing that listens on ports 80 and 443 and redirects requests to other services based on hostname. With this config, sails only ever listens on one port. If you don't need that functionality then there's no real reason (that I can think of) to switch.

Mind sharing what you changed in AssetController.js to extend the timeout period? I'd like to add the option to set the timeout in `config/local.js` for 1.0.0

**Comment by pwik** [comment]
Sure. In api/controllers/AssetController.js you've got this function "create" which handles the request to upload a new asset:

`req.file('file').upload(sails.config.files...`

Use the setTimeout method to set the request timeout to something else in ms.

    ...
    } else {
      return res.badRequest('Invalid version provided.');
    }
    
    // Set request timeout to 10 minutes
    req.setTimeout(10 * 60 * 1000);

    req.file('file').upload(sails.config.files...`  
    ...

https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback

By default this is set to 120000 ms, which is 2 minutes.

https://nodejs.org/api/http.html#http_server_timeout

**Comment by ArekSredzki** [comment]
Thanks @pwik, I'll add this in tonight :)
