### ISSUE TITLE
Version candidate undefined

### ISSUE THREAD

**Issue by andymartinwork** [ArekSredzki/electron-release-server#49]
I've tried this on latest master and on latest release:

I have two versions in my code, 2.0.0 and 2.0.1 - both osx_64
When I call the following URL: `localhost:1337/update/osx_64/2.0.0` I get this response:

```
debug: Update Search Query { platform: [ 'osx_64' ], version: '2.0.0', channel: 'stable' }
debug: Applicable Channels [ 'stable' ]
debug: Time Filter { '>': 2016-07-11T14:16:05.000Z }
debug: Newer Versions [ { assets: 
     [ { name: 'MyApp2.0.1.dmg',
         platform: 'osx_64',
         filetype: '.dmg',
         hash: '',
         size: 56474430,
         download_count: 0,
         fd: '/Users/andy/electron-versions/8b2c19d4-9265-4333-bd92-028afceafc87.dmg',
         createdAt: '2016-07-11T14:16:33.000Z',
         updatedAt: '2016-07-11T14:16:33.000Z',
         version: '2.0.1' } ],
    channel: 'stable',
    name: '2.0.1',
    notes: 'dsgs',
    createdAt: '2016-07-11T14:16:22.000Z',
    updatedAt: '2016-07-11T14:16:22.000Z' } ]
debug: Version candidate undefined
debug: Current version 2.0.0
debug: Version candidate denied
```

It looks like the latest version is undefined, but I can't see how it's possible for me to influence what the main version is?

**Comment by ArekSredzki** [comment]
Hi Andy,
Updates must be provided in the zip format, the dmg files are only served to users for new installs

**Comment by gokatz** [comment]
```info: Applying disable cache policy
debug: Update Search Query { platform: [ 'osx_64' ], version: '1.0.0', channel: 'stable' }
debug: Applicable Channels [ 'stable' ]
debug: Time Filter { '>': 2017-05-24T12:16:06.000Z }
debug: Newer Versions []
debug: Version candidate undefined
debug: Current version 1.0.0
debug: Version candidate denied
```

but I'm having a new asset version (1.0.1)

![awesome electron desktop app 2017-05-24 18-08-50](https://cloud.githubusercontent.com/assets/15158776/26403531/40ba866c-40ac-11e7-94f2-62802b744fd1.png)

Am I missing something?

**Comment by denis796** [comment]
Hello, same kind of issue as mentionned above.
I have the following result from a query. I don't understand why there is no candidate
`debug: Update Search Query { platform: [ 'windows_32' ],                                                                                                                                                    
  version: '0.1.0',                                                                                                                                                                                         
  channel: 'stable.yml' }                                                                                                                                                                                   
debug: Applicable Channels [ 'stable' ]                                                                                                                                                                     
debug: Time Filter { '>': 2021-06-29T13:05:22.000Z }                                                                                                                                                        
debug: Newer Versions [ { assets:                                                                                                                                                                           
     [ { name: 'My trial App Setup 0.2.0.exe',                                                                                                                                                              
         platform: 'windows_32',                                                                                                                                                                            
         filetype: '.exe',                                                                                                                                                                                  
         hash: '',                                                                                                                                                                                          
         size: 58858221,                                                                                                                                                                                    
         download_count: 0,                                                                                                                                                                                 
         fd: '/tmp/5f15c9fd-ad2a-4435-9b7c-fd003557368d.exe',                                                                                                                                               
         createdAt: '2021-06-29T13:17:03.000Z',                                                                                                                                                             
         updatedAt: '2021-06-29T13:22:27.000Z',                                                                                                                                                             
         version: '0.2.0' },                                                                                                                                                                                
       { name: 'My trial App Setup 0.2.0.exe.blockmap',                                                                                                                                                     
         platform: 'windows_32',                                                                                                                                                                            
         filetype: '.blockmap',                                                                                                                                                                             
         hash: '',                                                                                                                                                                                          
         size: 62965,                                                                                                                                                                                       
         download_count: 0,                                                                                                                                                                                 
         fd: '/tmp/36359628-8ee3-4f65-a74e-041ec5f8e1a6.blockmap',                                                                                                                                          
         createdAt: '2021-06-29T13:17:10.000Z',                                                                                                                                                             
         updatedAt: '2021-06-29T13:22:21.000Z',                                                                                                                                                             
         version: '0.2.0' } ],                                                                                                                                                                              
    channel: 'stable',                                                                                                                                                                                      
    name: '0.2.0',                                                                                                                                                                                          
    notes: '',                                                                                                                                                                                              
    createdAt: '2021-06-29T13:16:48.000Z',                                                                                                                                                                  
    updatedAt: '2021-06-29T13:16:48.000Z' } ]                                                                                                                                                               
debug: Version candidate undefined                                                                                                                                                                          
debug: Current version 0.1.0                                                                                                                                                                                
debug: Version candidate denied   `

Could you help me ?
