### ISSUE TITLE
local.js is not found in config folder

### ISSUE THREAD

**Issue by junjunruan** [ArekSredzki/electron-release-server#5]
After fork the repository, run `npm install`, I didn't find local.js file in config folder.

When I run `npm start`, it tell me this error: `Cannot read property 'config' of undefined`.

Can I use AWS S3 replace of using electron-release-server?

**Comment by ArekSredzki** [comment]
Hi!
Please see the [deployment documentation](https://github.com/ArekSredzki/electron-release-server/blob/master/docs/deploy.md) for further details on getting your server up and running.

Note that you must create a `config/local.js` file by copying `config/local.template`

You cannot use AWS S3 to _replace_ `electron-release-server`, but you can use AWS S3 **with** this application for hosting your assets.

If you look at [this line](https://github.com/ArekSredzki/electron-release-server/blob/master/api/services/AssetService.js#L17), you can see that I am using [skipper-disk](https://github.com/balderdashy/skipper-disk) for interfacing with the filesystem.
You could use [skipper-s3](https://github.com/balderdashy/skipper-s3) with very little extra work! :)
