### ISSUE TITLE
Nginx and Amazon ELB blocking websocket connections

### ISSUE THREAD

**Issue by bommuraj2012** [ArekSredzki/electron-release-server#50]
Thank you very much for electron release server , It works great !

We tried to use nginx as webserver , and we followed the documentation.
And noticed below issues.
  - When i click "show all versions" , it shows nothing.
  - Authentication fails too.

So we took OFF the ngnix and placed amazon Load balancer in front of electron release server.
Means, Amazon ELB receives connections from user and send it to electron release server.
BUT still we got below issues.
   - When i click "show all versions" , it shows nothing.
    - Authentication fails too.

Without Ngnix or Amazon ELB , Electron Release server works fine.
am i missing anything ?  any advise would highly appreciable !

Thanks,
Bommuraj

**Comment by ArekSredzki** [comment]
Hey :)
Sounds like the websockets aren't connecting.
What is the console output in devtools?
Is it connecting?

**Comment by bommuraj2012** [comment]
ArekSredzki, Thank you very much for your  reply !
I am able to see  **established session** between **amazon ELB and Server port 1337.**

**electron-release-server# npm start**

> electron-release-server@1.1.1 start /usr/local/electron-release-server
> node app.js

info:
info:                .-..-.
info:
info:    Sails              <|    .-..-.
info:    v0.12.3             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------'
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info:
info: Server lifted in `/usr/local/electron-release-server`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: -------------------------------------------------------
debug: :: Fri Jul 15 2016 18:49:55 GMT+0000 (UTC)

debug: Environment : development
debug: Port        : 1337
debug: -------------------------------------------------------




**electron-release-server# lsof -i:1337**
COMMAND   PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
node    32750 root   13u  IPv6 18414665      0t0  TCP ip-10-152-40-122.ec2.internal:1337->ip-10-45-87-241.ec2.internal:6163 (ESTABLISHED)
node    32750 root   15u  IPv6 18414687      0t0  TCP ip-10-152-40-122.ec2.internal:1337->ip-10-45-87-241.ec2.internal:6165 (ESTABLISHED)
node    32750 root   19u  IPv6 18413305      0t0  TCP *:1337 (LISTEN)
node    32750 root   20u  IPv6 18413350      0t0  TCP ip-10-152-40-122.ec2.internal:1337->ip-10-45-87-241.ec2.internal:6132 (ESTABLISHED)
node    32750 root   21u  IPv6 18414654      0t0  TCP ip-10-152-40-122.ec2.internal:1337->ip-10-154-189-62.ec2.internal:37905 (ESTABLISHED)
node    32750 root   23u  IPv6 18413516      0t0  TCP ip-10-152-40-122.ec2.internal:1337->ip-10-45-87-241.ec2.internal:6145 (ESTABLISHED)
node    32750 root   24u  IPv6 18413517      0t0  TCP ip-10-152-40-122.ec2.internal:1337->ip-10-45-87-241.ec2.internal:6146 (ESTABLISHED)
node    32750 root   25u  IPv6 18413558      0t0  TCP ip-10-152-40-122.ec2.internal:1337->ip-10-45-87-241.ec2.internal:6147 (ESTABLISHED)
node    32750 root   26u  IPv6 18413559      0t0  TCP ip-10-152-40-122.ec2.internal:1337->ip-10-45-87-241.ec2.internal:6148 (ESTABLISHED)
node    32750 root   27u  IPv6 18414596      0t0  TCP ip-10-152-40-122.ec2.internal:1337->ip-10-45-87-241.ec2.internal:6154 (ESTABLISHED)
node    32750 root   28u  IPv6 18414652      0t0  TCP ip-10-152-40-122.ec2.internal:1337->ip-10-45-87-241.ec2.internal:6156 (ESTABLISHED)

Thanks,
Bommuraj

**Comment by ArekSredzki** [comment]
Hi Bommuraj,
I was referring to the console in your browser.
### In Chrome:
#### Windows/Linux
`Ctrl + Shift + J`
#### Mac
`Cmd + Opt + J`

**Comment by bommuraj2012** [comment]
Oh Ok !  I got below lines in browser console.

WebSocket connection to 'wss://btnextupdate-1057138285.us-east-1.elb.amazonaws.com/socket.io/?__sail…tform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
sails.io.js:438  
        Socket is trying to reconnect to Sails...
_-|>_-  (attempt #1)


sails.io.js:14 WebSocket connection to 'wss://btnextupdate-1057138285.us-east-1.elb.amazonaws.com/socket.io/?__sail…tform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
sails.io.js:438  
        Socket is trying to reconnect to Sails...
_-|>_-  (attempt #2)


sails.io.js:14 WebSocket connection to 'wss://btnextupdate-1057138285.us-east-1.elb.amazonaws.com/socket.io/?__sail…tform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
sails.io.js:438  
        Socket is trying to reconnect to Sails...
_-|>_-  (attempt #3)


sails.io.js:14 WebSocket connection to 'wss://btnextupdate-1057138285.us-east-1.elb.amazonaws.com/socket.io/?__sail…tform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
sails.io.js:438  
        Socket is trying to reconnect to Sails...
_-|>_-  (attempt #4)


Thanks,
Bommuraj

**Comment by ArekSredzki** [comment]
Yeah, so you have to look into how to allow websocket reverse proxy through ELB.
I can't really help you from here though as it's not an issue with the release server.
Once you figure it out, consider opening a PR with the config required :)

**Comment by dengelke** [comment]
I've managed to fix this bug - you need to use the new application load balancer which has ws support in front of the EC2 instance instead of using an elastic load balancer.

To fix put the following files in a .ebextensions folder in the root of your project folder, specifying your domain and SSL cert (if required)

**proxy.config**
```
files:
  /etc/nginx/conf.d/proxy.conf:
    mode: "000644"
    owner: root
    group: root
    content: |
      upstream nodejs {
        server 127.0.0.1:8081;
        keepalive 256;
      }

      server {
        client_max_body_size 500M;
        listen 8080;
        server_name  download.yourdomain.com;

        if ($time_iso8601 ~ "^(\d{4})-(\d{2})-(\d{2})T(\d{2})") {
            set $year $1;
            set $month $2;
            set $day $3;
            set $hour $4;
        }
        access_log /var/log/nginx/healthd/application.log.$year-$month-$day-$hour healthd;
        access_log  /var/log/nginx/access.log  main;

        location / {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwared-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;

            proxy_pass http://127.0.0.1:8081/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        gzip on;
        gzip_comp_level 4;
        gzip_types text/html text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        location /static {
            alias /var/app/current/static;
        }
      }

container_commands:
 removeconfig:
    command: "rm -f /tmp/deployment/config/#etc#nginx#conf.d#00_elastic_beanstalk_proxy.conf /etc/nginx/conf.d/00_elastic_beanstalk_proxy.conf"
```

**alb-default-process.config**
```
option_settings:
  aws:elasticbeanstalk:environment:process:default:
    DeregistrationDelay: '20'
    HealthCheckInterval: '15'
    HealthCheckPath: /
    HealthCheckTimeout: '5'
    HealthyThresholdCount: '3'
    UnhealthyThresholdCount: '5'
    MatcherHTTPCode: null
    Port: '80'
    Protocol: HTTP
    StickinessEnabled: 'true'
    StickinessLBCookieDuration: '43200'
```
**application-load-balancer.config**
```
option_settings:
  aws:elasticbeanstalk:environment:
    LoadBalancerType: application
```
**alb-secure-listener.config** (optional for https support)
```
option_settings:
  aws:elbv2:listener:443:
    DefaultProcess: https
    ListenerEnabled: 'true'
    Protocol: HTTPS
    SSLCertificateArns: arn:aws:acm:your:super:secret:SSL:cert
  aws:elasticbeanstalk:environment:process:https:
    HealthCheckPath: /
    Port: '80'
    Protocol: HTTP
```
