### ISSUE TITLE
Auto-updating on OSX always response with 204

### ISSUE THREAD

**Issue by Chenimal** [ArekSredzki/electron-release-server#53]
In the client I setup as:

`updater.setFeedURL('http://127.0.0.1:1337/update/osx/1.2.0?v=1.2.0');`

And I got the log on the server side:

> debug: Update Search Query { platform: [ 'osx_64' ], version: '1.2.0', channel: 'stable' }
debug: Applicable Channels [ 'stable' ]
debug: The specified `version` does not exist
debug: Time Filter undefined
debug: Newer Versions [ { assets:
     [ { name: 'myapp-1.5.0.dmg',
         hash: '',
         filetype: '.dmg',
         fd: '/data1/web/local/app-releaser/.tmp/uploads/clients/9188cb5c-2813-402e-bd9a-89eac3635365.dmg',
         size: 57956105,
         version: '1.4.0',
         platform: 'osx_64',
         download_count: 0,
         createdAt: '2016-07-19T11:01:51.093Z',
         updatedAt: '2016-07-19T11:01:51.093Z' } ],
    channel: 'stable',
    name: '1.4.0',
    notes: 'test1',
    createdAt: '2016-07-15T09:34:15.677Z',
    updatedAt: '2016-07-15T09:34:15.677Z' } ]
debug: Version candidate undefined
debug: Current version undefined
debug: Version candidate denied

According to the log, it actually has a new version, but it also says 

> debug:Version candidate undefined
debug: Current version undefined
debug: Version candidate denied

and return 204.

Is there anything wrong with my settings?

Thanks!

**Comment by ArekSredzki** [comment]
The release server must contain the version you're upgrading from. 1.2.0 is not on the server

Also, the "?v=1.2.0" part of the feed URL is redundant.

**Comment by Chenimal** [comment]
Thanks for replying, Arek.

I tried using url like this: 
`updater.setFeedURL('http://127.0.0.1:1337/update/osx/1.4.0');`

And this is the server log:

> debug: Update Search Query { platform: [ 'osx_64' ], version: '1.4.0', channel: 'stable' }
debug: Applicable Channels [ 'stable' ]
debug: Time Filter { '>': Fri Jul 15 2016 17:34:15 GMT+0800 (CST) }
debug: Newer Versions [ { assets:
     [ { name: '金融圈-1.5.0.dmg',
         hash: '',
         filetype: '.dmg',
         fd: '/data1/web/local/fx-client-releaser/.tmp/uploads/clients/7335178f-de7d-4654-a040-02806abd41c4.dmg',
         size: 57956105,
         version: '1.5.0',
         platform: 'osx_64',
         download_count: 0,
         createdAt: '2016-07-20T06:08:08.822Z',
         updatedAt: '2016-07-20T06:08:08.822Z' } ],
    channel: 'stable',
    name: '1.5.0',
    notes: '',
    createdAt: '2016-07-20T06:07:00.524Z',
    updatedAt: '2016-07-20T06:07:00.524Z' } ]
debug: Version candidate undefined
debug: Current version 1.4.0
debug: Version candidate denied

and still return 204. I created two versions(1.4.0&1.5.0) and both have mac assets.

Not sure why it doesn't work. 

Thanks

**Comment by Chenimal** [comment]
I found the reason. In 'api/controllers/VersionController.js', only '.zip' files are considered version assets:

> newVersion.assets = _.filter(newVersion.assets, function (asset) {
                  return asset.filetype === '.zip';
                });

If only .dmg is uploaded, it wont trigger 'update-available' event.

**Comment by justechn** [comment]
I am running into this also. Does this mean we need both a .dmg and a .zip, or will a .zip on its own work?

**Comment by Lorempn2** [comment]
Ran into the same issue using electron-forge and electron-release-server. You have to provide both a zip and a dmg to get the update functionality working for dmg @ osx :)

**Comment by ramibadran** [comment]
Hi Guys

Im facing the same issue ,response always 204 ,i have uploaded 2 pkgs version (dmg and zip) and still the same 
can someone help?
