### ISSUE TITLE
WebSocket  error

### ISSUE THREAD

**Issue by bommuraj2012** [ArekSredzki/electron-release-server#54]
Hi, 

I  have added nginx as webserver But i could not find any **asset** on download page.
Also i am seeing below error on browser console.

WebSocket connection to 'ws://ec2-54-205-65-189.compute-1.amazonaws.com/socket.io/?__sails_io_sdk_version=0.13.8&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: WebSocket is closed before the connection is established.

Any suggestion would be highly appreciable.

Thanks and Regards,
Bommuraj Paramaraj

**Comment by ArekSredzki** [comment]
Hi Bommuraj,
This is the same issue as #50 
This is not an issue with the release server but rather with your server configuration.

Either:
a) your firewall blocks websockets
b) your nginx install is not [set up to reverse proxy websocket requests](https://github.com/ArekSredzki/electron-release-server/blob/master/docs/deploy.md)

**Comment by dengelke** [comment]
The issue is due to using the classic elastic load balancer (the aws default) which has no websocket support, you need to upgrade to using the application load balancer which has websocket support - see the solution referenced in #50
