### ISSUE TITLE
MongoDb instead of PostgreSql, sessions?

### ISSUE THREAD

**Issue by jvdonk** [ArekSredzki/electron-release-server#59]
When using the sails-mongo adapter it's easy to configure electron-release-server to use mongodb instead of postgresql for storing versions and assets.

package.json:
```
"dependencies": {
...
    "sails-postgresql": "^0.12.1", // not used anymore, instead:
    "sails-mongo": "^0.12.0", // new adapter
    "connect-mongodb-session": "^1.1.1", // used for session.js, see below
...
  },
```

local.js:
```
  connections: {
    postgresql: {
      adapter: 'sails-mongo', // was: 'sails-postgresql'
      host: 'localhost',
      port: 27017,
      user: '',
      password: '',
      database: 'electron_release_server'
    }
  },
```

But what about sessions? Not sure where, when and why they are used but some configuration is available for it.

local.js:
```
session: {
    // Recommended: 63 random alpha-numeric characters
    // Generate using: https://www.grc.com/passwords.htm
    secret: 'LE8wNW5oTFbJZqJtfitHRPkcsdOaybamQ9cWkovbLJPh8DjfTGCQeNCaEZvxpGQ',
    database: 'electron_release_server_sessions',
    host: 'localhost',
    port: 27017
  },
```

session.js:
```
module.exports.session = {
  adapter: 'connect-mongodb-session',
  url: 'mongodb://:localhost:27017/electron_release_server_session'
};
```

With these settings I can add versions with assets in the admin(http://localhost:1337/admin) and request the frontend (http://localhost:1337/update?platform=Windows%2064%20bit) and notice that there is a 'test' mongo-database created with a sessions collection:

![image](https://cloud.githubusercontent.com/assets/1164988/17168294/f1d56d44-53e1-11e6-868e-79fc9e6c95dd.png)

So where does this 'test' come from and why isn't it 'electron_release_server_sessions' like configured in the session in local.js and in the mongodb-url in session.js.

Thank you for your effort and awesome project!

**Comment by ArekSredzki** [comment]
@jvdonk Sorry for the slow response. I hope that you were able to figure this out.

The [sails docs](http://sailsjs.org/documentation/reference/configuration/sails-config-session) suggest using `connect-mongo` not `connect-mongo-session`.

They also show you what config options are available.
I'd suggest reaching out to the sails community in regards to this issue as it's not specific to the release server :)

Happy coding!
