### ISSUE TITLE
HTTPS download URLS

### ISSUE THREAD

**Issue by PierBover** [ArekSredzki/electron-release-server#74]
When using an HTTPS URL to get updates the returned JSON doesn't put HTTPS in the URLs for downloading the files.

**Comment by ArekSredzki** [comment]
The base URL used in the download URLs is determined by what you specified as `appUrl` in `config/local.js`

**Comment by PierBover** [comment]
Thanks @ArekSredzki !

I'll update the docs with this info.

**Comment by ArekSredzki** [comment]
Thanks @PierBover !
