### ISSUE TITLE
create docker image and docker-compose.yml

### ISSUE THREAD

**Issue by mnewmedia** [ArekSredzki/electron-release-server#77]
Create docker image with update server and docker-compose.yml for database. So users only have to copy-paste the docker-compose.yml run and use it.

**Comment by ArekSredzki** [comment]
Hi @mnewmedia 
I personally don't have the time to set this up, but it'd be a great feature to have. If you create such a file, please open a PR.

**Comment by mnewmedia** [comment]
just found a [fork](https://github.com/EvgeneOskin/electron-release-server) of this project which has added all the docker stuff, maybe @EvgeneOskin will send a PR. :)

**Comment by miyurusagarage** [comment]
+1
