### ISSUE TITLE
programmatically adding assets on electron release server

### ISSUE THREAD

**Issue by gopikrishnaA** [ArekSredzki/electron-release-server#79]
I need to upload the assets programmatically on ERS. Do we have any rest api for uploading the assets.
Steps:
1. Need the authentication api for admin access to ERS client. 
2. Need the creating version api on ERS. 
3. If it has any Oauth token mechanism to upload assets?

Please share the details and Thanks in advance.

**Comment by ArekSredzki** [comment]
I'm going to assume that you're not talking about a `European Remote-sensing Satellite`. Mind clarifying what ERS is? I don't think it's a common acronym...

Banter aside:
1. The UI for this site is a single page web app. As such, everything is done via API endpoints. When you log into the admin panel the auth service (`api/services/AuthService.js`) is used to validate your credentials and generate a Java Web Token. Said token is then used by the ui to authenticate all operations that require it, such as uploading assets. The auth token middleware is defined in `api/policies/authToken.js`. If you're doing it programmatically, you'll probably want to replace the token logic with support for a static auth key.
2. there's a version API already, not sure what you mean
3. There's no OAuth used in this server, but you can add it if you'd like; though I don't see why you would for doing this programmatically.

**Comment by gopikrishnaA** [comment]
I don't want to upload assets manually on ERS and need to upload assets by the rest api using shell or javascript.

**Comment by ArekSredzki** [comment]
Your response hasn't clarified anything regarding your question...

**Comment by gopikrishnaA** [comment]
I required to upload assets automatically on server. Rest api is in the form of http://localhost:8080/api/auth/login?username=admin&password=xxxxxx
http://cdknotify.releases01-dev.las.dsghost.net/api/version

similar to above api I like to know about uploading assets api?

**Comment by gopikrishnaA** [comment]
https://github.com/ArekSredzki/electron-release-server/issues/36 As per mentioned in this issue I . I am unable to upload assets to the electron release server. facing issue as version is required and file was not uploaded.

**Comment by ArekSredzki** [comment]
As I stated previously, `http://localhost:8080/api/auth/login?username=admin&password=xxxxxx` returns a java web token. You can use that to authenticate other requests. To do so, add it to your requests as a `Bearer` authentication header. #36 is an example of how to do that.

**Comment by gopikrishnaA** [comment]
But as per mentioned in the #36 .I am unable to upload the assets.

**Comment by ArekSredzki** [comment]
Well does the version exist? ... you have to create the version with a separate request prior to uploading assets

**Comment by gopikrishnaA** [comment]
yes version exists in the ERS

**Comment by ArekSredzki** [comment]
You *still* haven't clarified what ERS stands for. It isn't a common acronym, you can't use obscure acronyms as if everyone knows what they mean.

What code are you using to invoke the automated upload?

**Comment by gopikrishnaA** [comment]
I am using shell script,  requesting http api using Curl.

curl -X POST -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTQ3NDYzMzE2MX0.O1MIPZTLSoX6YRUlR_X_SBT91z4BQaomdDMEBCyDZrY' -H "Content-Type:multipart/form-data" -d {"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTQ3NDYzMzE2MX0.O1MIPZTLSoX6YRUlR_X_SBT91z4BQaomdDMEBCyDZrY","version": "1.0.0","platform": "windows_64", "file": "@/Users/akkumahg/Desktop/yetinotify/yeti-notify/dist/win/cdknotify-1.0.0.exe"}--write-out %{http_code} --silent --output /dev/null "http://cdknotify.releases01-dev.las.dsghost.net/api/asset"

**Comment by ArekSredzki** [comment]
Providing the path to a file is not the same as uploading the file... Thus, the uploaded asset is invalid. I believe you have to prefix the path with `@`

**Comment by gopikrishnaA** [comment]
I uploaded with "file": "@/Users/akkumahg/Desktop/yetinotify/yeti-notify/dist/win/cdknotify-1.0.0.exe". Even though I am facing with same error

**Comment by ArekSredzki** [comment]
First off, you're uploading an asset with the same name as an existing asset.

Secondly, you should use `-F` for the form data rather than `-d`.
https://curl.haxx.se/docs/manpage.html#-F

**Comment by jvdonk** [comment]
Lol, ERS stands for Electron Release Server. 

Like @ArekSredzki  said:

GET /api/auth/login?username=admin&password=xxxxxx
You receive a token:
```
{
  "user": "admin",
  "token": "eyJhbGXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}
```

POST /api/version to create a new version
with Authorization header containing the token mentioned above, and the following HTTP body:
```
{
  "name":"1.0.3",
  "notes":"",
  "channel":{
    "name":"stable"
  }
}
```

Which gives the folowing response that the version is created:
```
{
  "name": "1.0.3",
  "notes": "",
  "channel": "stable",
  "createdAt": "2016-11-26T14:53:16.463Z",
  "updatedAt": "2016-11-26T14:53:16.463Z",
  "id": "5839a1dc9114b8ec07a65fd3"
}
```

POST /api/asset to upload a new asset
with again Authorization header with the token and the following form data:
version: 1.0.3
platform: windows_64
file: the asset

which should give the following response:
```
{
  "name": "filename.exe",
  "hash": "",
  "filetype": ".exe",
  "fd": "C:\\DEV\\Test\\electron-release-server\\.tmp\\uploads\\PATH_FOR_ASSETS\\205d0ba6-9a64-459c-a06f-4460544d6ad5.exe",
  "size": 37329135,
  "version": "1.0.3",
  "platform": "windows_64",
  "download_count": 0,
  "createdAt": "2016-11-26T15:10:50.573Z",
  "updatedAt": "2016-11-26T15:10:50.573Z",
  "id": "5839a5fa9f2e54a81ce3cc5d"
}
```

Done! :) Works nicely. ( Tested with Postman )

Next step, for me, is to integrate it with an automated build/deploy pipeline: TeamCity/OctopusDeploy. But that should work.

**Comment by rgl** [comment]
FYI I've created an example python client that uses the API to publish an application version/asset at https://github.com/rgl/electron-release-server-vagrant/blob/master/publish.py (BTW, that repo also contains code to create an ERS installation and ubuntu/windows/macos clients. all in a vagrant environment)

**Comment by ArekSredzki** [comment]
@rgl Neat! If you add a PR linking to that repo in the docs I'll gladly merge it.
That said, I would highly recommend using docker for the ERS instance.

**Comment by saascentral** [comment]
How about deleting a version? Can someone provide the endpoint/sample to delete a version?
