### ISSUE TITLE
Support multiple builds for linux

### ISSUE THREAD

**Issue by gregaubert** [ArekSredzki/electron-release-server#81]
It would be nice to allow the user to choose between multiple builds for linux.
Actually if I upload for exemple 3 builds (`.deb`, `.tar.gz`, `.AppImage`) for linux, the user won't be able to choose which one he wants, he'll only be able to download the `.deb`.

**Comment by ArekSredzki** [comment]
Hi @gregaubert 
This would be an awesome feature to add.
If you (or anyone else reading this) would like to help, I'll gladly answer any questions that arise in implementing this.

**Comment by gregaubert** [comment]
Okay, I'll try to look into it if I can find a bit of time!
