### ISSUE TITLE
Support `-delta` updates

### ISSUE THREAD

**Issue by wojtkowiak** [ArekSredzki/electron-release-server#82]
A feature request and a question in one :)
I was just wondering why this is not supported.
If you could give me some hints I could probably do a PR for that.

**Comment by ArekSredzki** [comment]
Hey @wojtkowiak!
Good question.
The reason as to why `electron-release-server` doesn't support delta updates is pretty simple: I didn't need them.

That said, it'd be a nice feature to support!

When I was working on an electron app, electron-userland/electron-builder didn't support creating delta updates (I don't think it does to this day), and even if it did, I think that only Squirrel.Windows supports them.

However, if you decide that you'd like to take this up, I'll gladly answer any questions you may have.

**Comment by wojtkowiak** [comment]
Well the reason why I am asking is just because I went through all the options electron-builder offers and along the way I have managed to generate the delta updates. So it seems it is now supported. It even works nicely with your server :wink: - it downloads the latest release and creates the delta file.
Yes, this is probably only for Windows, however I did not try to work with mac environment yet.
I will take a look at it next week.

**Comment by ArekSredzki** [comment]
@wojtkowiak That's awesome! I hadn't even really thought about it, but yeah, theoretically it should work just fine! If it really does, please let me know so that it can be added to the readme :)

Question: Do the delta updates only work from the immediately previous release?

**Comment by MarshallOfSound** [comment]
@ArekSredzki Delta updates do only work for the previous release but I believe the deltas can be chained to generate a release further in the future.  I.e. Apply two deltas to obtain the full package for two updates down the line.

**Comment by ArekSredzki** [comment]
@MarshallOfSound Thanks for chiming in about that :)

With that in mind, there's an edge case that might be problematic.
The release server looks for versions that are the same or newer than the one you've requested from. Then, it generates a `RELEASES` file for the relevant assets that belong to the *newest* applicable release (it must have at least one relevant asset). Generally, this works totally fine and it results in less data transmission and cheaper `RELEASES` file generation (marginally).
The issue with this is that if there is a release between the one you have (1.0.0) and the latest (1.0.2), only the delta from 1.0.1 to 1.0.2 will be included in the file, the one from 1.0.0 to 1.0.1 will not be offered.

**Comment by MarshallOfSound** [comment]
@ArekSredzki The spec dictates that all available releases should be included in the RELEASES file though.  In fact, when generating delta updates the generated RELEASES file includes all previous versions of the application for me.

Server side I only send out the most recent 10 or so updates I think to save space (no point sending out information for 2 year old updates).  You can see what I send here https://update.gpmdp.xyz/update/win/3.5.0/RELEASES

**Comment by ArekSredzki** [comment]
@MarshallOfSound Correct, but that requirement is alleviated since the `RELEASES` file is generated dynamically with the knowledge of the client's current version. I or someone nice enough to submit a PR has to simply include all delta updates contained in the equal or newer versions.
