### ISSUE TITLE
System.Net.WebException: The remote server returned an error: (404) Not Found.

### ISSUE THREAD

**Issue by adrianscripcariu** [ArekSredzki/electron-release-server#83]
Hello, Can anyone please help me :)

I have configured the electron-release-server
http://download.myapp.com/update/win32/:version/:channel

My feedUrl looks like http://localhost:1337/update/win32/1.0.0

If i upload the version 1.0.0 
![1 0 0](https://cloud.githubusercontent.com/assets/21836226/19311780/70d53230-9098-11e6-8239-bd603abf5cb8.png)
and open the installed version 1.0.0 it gives me it shows in  console.log("update-not-available");

ok

but if i upload the next version 1.0.1 

![1 0 1](https://cloud.githubusercontent.com/assets/21836226/19311858/beb489f6-9098-11e6-804b-05ad11d92779.png)

in the console it gives me 404 not found
![1 0 3](https://cloud.githubusercontent.com/assets/21836226/19311909/e328d5e4-9098-11e6-9796-ccae14af6524.png)

Could anyone help me what I have done wrong?

if there is only 1.0.0 version on server this is how the log from server looks like

![1 0 4](https://cloud.githubusercontent.com/assets/21836226/19312353/ab59fa56-909a-11e6-91db-90d86d21895c.png)

and for 1.0.0 installed and 1.0.1 on server this is how it looks

![1 0 5](https://cloud.githubusercontent.com/assets/21836226/19312445/0701eb2a-909b-11e6-96c3-b645989c6db6.png)

Many thanks.

**Comment by ArekSredzki** [comment]
Hi @adrianscripcariu

Sorry to hear that you're having such troubles! I'll do my best to try to resolve them.

When you set your feed URL to `http://localhost:1337/update/win32/1.0.0`, Squirrel.Windows will actually evaluate `http://localhost:1337/update/win32/1.0.0/RELEASES`.

If you use Postman to send a request to this URL with and without relevant update assets, what are the responses?

**Comment by adrianscripcariu** [comment]
Hello, I tested the links in POSTMAN

If the call is http://localhost:1337/update/win64/1.0.0 
and there is only 1.0.0 version on server 
it returns nothing


If the call is http://localhost:1337/update/win64/1.0.0/RELEASES 
and there is only 1.0.0 version on server 
it returns F23EA70E706A228D7A14AA0173040248BE98048D http://localhost/download/1.0.0/windows_64/app-1.0.0-full.nupkg 59340938

and in the app console is shows ("update-not-available");

![zzz123](https://cloud.githubusercontent.com/assets/21836226/19341088/afc7103e-9134-11e6-8ec5-4d7a2d727d59.png)


If i upload 1.0.1 on server 
If the call is http://localhost:1337/update/win64/1.0.0
it returns nothing

If the call is http://localhost:1337/update/win64/1.0.0/RELEASES
it returns 26A45A8D6D8DCC822FB1923BE8128FDD8452B4A4 http://localhost/download/1.0.1/windows_64/app-1.0.1-full.nupkg 59340939
but in app console it shows The remote server returned an error: (404) Not Found.

![zzz12344](https://cloud.githubusercontent.com/assets/21836226/19341226/3dd83164-9135-11e6-8768-ac5b61771618.png)

**Comment by adrianscripcariu** [comment]
Hello again 

I took a look into the server and found this
if it is localhost
If the call is http://localhost:1337/update/win64/1.0.0/RELEASES
and returns
http://localhost/download/1.0.1/windows_64/app-1.0.1-full.nupkg 59340939

localhost is without a port and this is why it gives 404.

I modified in versionController.js for the moment to use the port for localhost
   // Change asset name to use full download link
  assets = _.map(latestVersion.assets, function(asset) {
              asset.name = url.resolve(
                sails.config.appUrl + ":1337",
                '/download/' + latestVersion.name + '/' + asset.platform + '/' +
                asset.name
              );

and now it is ok :)

![assets](https://cloud.githubusercontent.com/assets/21836226/19350058/e66efd0c-915e-11e6-9cf5-a5deb01e535c.png)

**Comment by ArekSredzki** [comment]
@adrianscripcariu Good catch :)
However, the *following information is important*
Instead of modifying `VersionController.js`, you should modify `appUrl` in `config/local.js`.
Otherwise, you'll have a bad time deploying this.

**Comment by manpreetrsystems** [comment]
@ArekSredzki What should be the appurl in config/local.js??

Like I have uploaded new version of my application on electron release server and while hitting this url "**http://localhost/download/0.0.2/windows_64/Simple.Updater.Example.Setup.0.0.2.exe**" , I am able to download the exe in my browser.
And should be the url in updates.json which too I have uploaded on electron release server.
