### ISSUE TITLE
Tips for people struggling

### ISSUE THREAD

**Issue by msholly** [ArekSredzki/electron-release-server#84]
Just got done trying to get this setup. Here's some things I had to figure out on my own, and hopefully it helps someone.

For those trying to install on DigitalOcean - this tutorial helped immensely. Since you'll need a NGINX and NodeApp running on the same machine, and this repro assumes you already have it setup.
https://www.youtube.com/watch?v=kR06NoSzAXY

Also the $5 a month 512Mb droplet isn't enough RAM to install the app dependencies. 

I made a pull request for an incorrect database string on the Database doc as well. Could be causing a few database error issues for users. 

Great app, love what it promises to do for my software workflow!

**Comment by ArekSredzki** [comment]
Thanks for the insight @msholly!
In order to make these tips more readily available to new users, mind creating a PR that adds a tips page and links to it from the appropriate places within the current documentation?
Thanks :)

**Comment by msholly** [comment]
Sure! Hope its ok if I link to that tutorial. I'm obviously not affiliated with him at all.

**Comment by ArekSredzki** [comment]
But of course :)
