### ISSUE TITLE
Multiple Application Support

### ISSUE THREAD

**Issue by PreDeToR** [ArekSredzki/electron-release-server#85]
Hi Guys

Is it possible to host multiple applications on the system for update, or would I need to run an instance for each application.

**Comment by ArekSredzki** [comment]
Hi @PreDeToR
Currently, only a single application is supported. There is already a feature request for this #33, but I don't believe that it is being actively developed. For now one must run multiple instances.

**Comment by ArekSredzki** [comment]
Try using the new Flavors feature
