### ISSUE TITLE
Auto-updater on OS X

### ISSUE THREAD

**Issue by adrianscripcariu** [ArekSredzki/electron-release-server#86]
Hello,

I have a question for OS x. 
it has feed url set as autoUpdater.setFeedURL('http://download.myapp.com/update/'+platform+'/'+version);

but I don't see the channel in example

If I use beta channel for osx as I do in windows it is not working.

Many thanks.

**Comment by ArekSredzki** [comment]
Hi, sorry for the slow response.
I've updated the docs [here](https://github.com/ArekSredzki/electron-release-server/blob/master/docs/update-osx.md).
Please ensure that you upload the `.zip` for updates.

If this issue persists, please re-open the ticket

**Comment by adrianscripcariu** [comment]
Hello and many thanks for the information... it stills helps me since we
haven't go on stable version :D
I tested it and it is ok.

Have a nice day.
