### ISSUE TITLE
integrate with CI

### ISSUE THREAD

**Issue by zh99998** [ArekSredzki/electron-release-server#88]
Is there any way to publish a release automatically so that I can trigger it from Appveyor or Travis CI?

**Comment by ArekSredzki** [comment]
Hi, sorry for the slow response.
This is definitely supported :) though not well documented.

I had this set up with Jenkins at Tesla, it was a little while ago so give me a bit to find the request you'll have to use.

**Comment by alexsorokoletov** [comment]
+1

**Comment by ArekSredzki** [comment]
@zh99998 @alexsorokoletov Sorry for the delay, please see #79 
I'll try to add docs for this later

**Comment by rgl** [comment]
I've created a script to publish a version/asset at https://github.com/rgl/electron-release-server-vagrant/blob/master/publish.py. Maybe that can help with the CI integration.

**Comment by ArekSredzki** [comment]
@rgl Thinking about it a bit more, would you be alright with moving that publish script into this repo that it can all be version controlled together? It'd be right at home under `/scripts`

**Comment by rgl** [comment]
I have no problem with that, but this was just a quick way for doing the publication, at least it should be changed to read the username and password from environment variables (as those should not appear on the CI logs). For integrating it here, should it be converted to JavaScript? As it is now, it requires python 3 and the requests library.

**Comment by ArekSredzki** [comment]
@rgl Awesome! Having a node version would be really great, but I suppose that having both can't hurt.

**Comment by rgl** [comment]
@ArekSredzki I've updated `publish.py` to read the username/password from environment variables and to use a POST/JSON request to authenticate with ERS. It can be used like:

```bash
export ERS_USERNAME=vagrant
export ERS_PASSWORD=vagrant
python publish.py stable 1.0.0 windows_64 dist/win/hello-world-setup_1.0.0_amd64.exe
```
