### ISSUE TITLE
Unable to create asset error during upload

### ISSUE THREAD

**Issue by ractoon** [ArekSredzki/electron-release-server#9]
Running into an odd issue after update - whenever I try to upload an asset to a version the progress bar appears and it begins to upload. After reaching ~35% it resets back to 0 and continues uploading. It does that a couple times and then stops and displays a notification with the error:

Unable to create asset
Unknown error occurred

Uploading smaller files it gets to ~20% and fails after one time.

In local.js the files section looks like:

```
files: {
  dirname: 'downloads',
  maxBytes: 524288000
}
```

The `downloads` directly is set up in the app folder with write permissions for the app/nginx.

Any tips on what could be causing this would be greatly appreciated.

Thanks!

**Comment by ArekSredzki** [comment]
Could you please attach the server log too? Thanks!

**Comment by ractoon** [comment]
@ArekSredzki Ahh, I had been looking at the wrong logs. Needed to add `client_max_body_size 500M` param to the nginx config. All appears to be working now. Sorry for the false alarm. Thanks again for the help and the handy app!

**Comment by ArekSredzki** [comment]
@ractoon Glad to hear that you figured it out and are enjoying the app 👍
