### ISSUE TITLE
URL not supported?

### ISSUE THREAD

**Issue by SantoDE** [ArekSredzki/electron-release-server#93]
Hey there,

I'm currently trying to setup auto updater with this server in my app as well. However, I have a weird issue.

When trying to perform an update from my app, I end up with an error event like "URL not supported". However, by calling the URL directly from e.g. my browser, all looks good to me.

Anyone encountered this issue already?

Regards,
SantoDE

**Comment by ArekSredzki** [comment]
@SantoDE Sorry for the delay.
Could you show me what url you are using in `setFeedURL`?

**Comment by ArekSredzki** [comment]
@SantoDE Ping
