### ISSUE TITLE
Packaging with electron-builder 

### ISSUE THREAD

**Issue by Ludea** [ArekSredzki/electron-release-server#98]
Hello, 

Is there a wiki or tutorial for packaging with electron-builder ? 
I try to setup this on Debian x64, it package,  but don't launch. 

I use the electron-builder  Quick starter guide. 
This issue is ENODIR is not a directory

**Comment by ArekSredzki** [comment]
Hello,
Please refer to the electron-builder repo for assistance in this regard since this isn't directly related to the release server itself.
Best of luck!
